import type { QuestionCard, AnswerCard } from '@/types/game'

export const QUESTIONS: QuestionCard[] = [
  { id: 1, text: "Una cosa simpatica, semplice e romantica da fare la sera di San Valentino è ___" },
  { id: 2, text: "Il modo migliore per rompere con qualcuno è ___" },
  { id: 3, text: "Cosa non dovresti mai dire al tuo capo? ___" },
  { id: 4, text: "Il segreto per un matrimonio felice è ___" },
  { id: 5, text: "La cosa più italiana del mondo è ___" },
  { id: 6, text: "Il momento peggiore della vita è ___" },
  { id: 7, text: "Cosa ti aspetti dalla vita dopo i 40 anni? ___" },
  { id: 8, text: "Il regalo perfetto per la suocera è ___" },
  { id: 9, text: "Come si sopravvive a una cena di Natale in famiglia? ___" },
  { id: 10, text: "La cosa più imbarazzante che può capitare in ascensore è ___" },
  { id: 11, text: "Il problema numero uno degli italiani è ___" },
  { id: 12, text: "Cosa fa un italiano quando è in crisi? ___" },
  { id: 13, text: "Il segreto del successo al bar è ___" },
  { id: 14, text: "Il rimedio della nonna per ogni malattia è ___" },
  { id: 15, text: "La cosa che un italiano fa meglio di tutti è ___" },
  { id: 16, text: "Come si riconosce un turista in Italia? ___" },
  { id: 17, text: "Il peggiore momento per chiamare la mamma è ___" },
  { id: 18, text: "Il modo migliore per fare bella figura a una cena è ___" },
  { id: 19, text: "Cosa non può mancare in una casa italiana? ___" },
  { id: 20, text: "Il peggior lavoro del mondo è ___" },
  { id: 21, text: "Come si fa a non pagare il conto al ristorante? ___" },
  { id: 22, text: "La cosa più difficile della vita moderna è ___" },
  { id: 23, text: "Perché le mamme italiane sono speciali? ___" },
  { id: 24, text: "Il momento in cui ti senti davvero italiano è ___" },
  { id: 25, text: "Cosa fa un nonno italiano nel pomeriggio? ___" },
  { id: 26, text: "Il modo peggiore per iniziare una dieta è ___" },
  { id: 27, text: "La scusa migliore per arrivare in ritardo è ___" },
  { id: 28, text: "Cosa succede quando finisce la pasta? ___" },
  { id: 29, text: "Come si trova parcheggio a Roma? ___" },
  { id: 30, text: "La cosa più assurda che fa un italiano all'estero è ___" },
  { id: 31, text: "Il modo migliore per evitare i parenti a Natale è ___" },
  { id: 32, text: "Perché gli italiani gesticolano? ___" },
  { id: 33, text: "La peggiore giustificazione per non andare in palestra è ___" },
  { id: 34, text: "Cosa succede se dici a un'italiana che il suo ragù non è buono? ___" },
  { id: 35, text: "Il momento più felice della settimana è ___" },
  { id: 36, text: "Come si capisce che sei innamorato? ___" },
  { id: 37, text: "Il peggior complimento che puoi fare a qualcuno è ___" },
  { id: 38, text: "Cosa fa un politico italiano quando perde le elezioni? ___" },
  { id: 39, text: "Il rimedio universale per tutti i problemi è ___" },
  { id: 40, text: "La cosa più strana che si trova in un frigorifero italiano è ___" },
  { id: 41, text: "Perché è impossibile stare a dieta in Italia? ___" },
  { id: 42, text: "Il modo più veloce per far arrabbiare un milanese è ___" },
  { id: 43, text: "Cosa non si fa mai in spiaggia? ___" },
  { id: 44, text: "Il peggior regalo di Natale che puoi ricevere è ___" },
  { id: 45, text: "Come si riconosce un italiano vero? ___" },
  { id: 46, text: "La cosa che fa invecchiare di più è ___" },
  { id: 47, text: "Cosa pensa un gatto del suo padrone? ___" },
  { id: 48, text: "Il modo migliore per perdere un amico è ___" },
  { id: 49, text: "Come si rompe il ghiaccio con qualcuno che non si conosce? ___" },
  { id: 50, text: "Il peggior modo per fare una proposta di matrimonio è ___" },
  { id: 51, text: "La peggiore cosa che può succedere a una festa è ___" },
  { id: 52, text: "Come si convincono i figli a mangiare la verdura? ___" },
  { id: 53, text: "Cosa succede quando il nonno trova internet? ___" },
  { id: 54, text: "La migliore scusa per non lavorare è ___" },
  { id: 55, text: "Il peggior consiglio che si possa dare a qualcuno è ___" },
  { id: 56, text: "Come si diventa famosi in Italia? ___" },
  { id: 57, text: "La cosa più noiosa che esiste è ___" },
  { id: 58, text: "Cosa succede in Italia alle 14:00? ___" },
  { id: 59, text: "Il peggior compagno di viaggio è ___" },
  { id: 60, text: "Come si reagisce quando cade la pasta? ___" },
  { id: 61, text: "Cosa fa un italiano in caso di neve? ___" },
  { id: 62, text: "Il modo migliore per sciupare una serata romantica è ___" },
  { id: 63, text: "Come si fa a capire che sei diventato vecchio? ___" },
  { id: 64, text: "La cosa più pericolosa della vita quotidiana è ___" },
  { id: 65, text: "Cosa fa il nonno quando si collega a Facebook? ___" },
  { id: 66, text: "Il modo migliore per essere licenziati è ___" },
  { id: 67, text: "Come si rovina un pranzo domenicale? ___" },
  { id: 68, text: "La scusa perfetta per non alzarsi dal divano è ___" },
  { id: 69, text: "Cosa succede al primo appuntamento quando non c'è feeling? ___" },
  { id: 70, text: "Il peggior modo per fare bella figura con i suoceri è ___" },
  { id: 71, text: "La cosa più ridicola che si fa per amore è ___" },
  { id: 72, text: "Cosa pensa veramente il cane quando lo guardi mangiare? ___" },
  { id: 73, text: "Il segreto di una buona pizza è ___" },
  { id: 74, text: "La cosa che tutti fanno ma nessuno ammette è ___" },
  { id: 75, text: "Cosa succede se proponi una pizza hawaiana a Napoli? ___" },
  { id: 76, text: "Il modo più creativo per litigare col vicino di casa è ___" },
  { id: 77, text: "Come si reagisce quando il Wi-Fi non funziona? ___" },
  { id: 78, text: "La cosa più drammatica che può succedere in vacanza è ___" },
  { id: 79, text: "Cosa fa un italiano quando incontra un connazionale all'estero? ___" },
  { id: 80, text: "Il peggior modo per fare una riunione di lavoro è ___" },
  { id: 81, text: "Come si sopravvive a un viaggio in treno in Italia? ___" },
  { id: 82, text: "La cosa più bella della vita è ___" },
  { id: 83, text: "Come si conquistano i genitori del/la fidanzato/a? ___" },
  { id: 84, text: "Il modo perfetto per iniziare il lunedì mattina è ___" },
  { id: 85, text: "Cosa ti fa capire che una relazione è finita? ___" },
  { id: 86, text: "Il peggior momento per fare una battuta è ___" },
  { id: 87, text: "Come si reagisce quando arriva la bolletta del gas a dicembre? ___" },
  { id: 88, text: "La cosa che nessun italiano ammetterà mai è ___" },
  { id: 89, text: "Il modo migliore per evitare il traffico a Milano è ___" },
  { id: 90, text: "Cosa succede durante il Derby di Milano? ___" },
  { id: 91, text: "Il peggior modo per chiedere un aumento è ___" },
  { id: 92, text: "Come si fa a sembrare più colti a una cena? ___" },
  { id: 93, text: "La cosa che manda più in crisi un italiano è ___" },
  { id: 94, text: "Il modo più italiano per risolvere un problema è ___" },
  { id: 95, text: "Cosa fa davvero paura a un italiano? ___" },
  { id: 96, text: "Come si capisce se sei al Sud o al Nord Italia? ___" },
  { id: 97, text: "La peggiore cosa da dire durante una lite di coppia è ___" },
  { id: 98, text: "Il modo più creativo per non pagare una multa è ___" },
  { id: 99, text: "Cosa succede quando gli azzurri vincono i mondiali? ___" },
  { id: 100, text: "Il segreto per essere sempre simpatici è ___" },
]

export const ANSWERS: AnswerCard[] = [
  { id: 1, text: "Chiamare la mamma" },
  { id: 2, text: "Una partita Juventus/Napoli con pizze e birre" },
  { id: 3, text: "La rottura delle acque" },
  { id: 4, text: "Cominciare con il dito, finire con il braccio" },
  { id: 5, text: "Il cornetto al bar" },
  { id: 6, text: "Piangere davanti al frigorifero" },
  { id: 7, text: "Un selfie con il suocero ubriaco" },
  { id: 8, text: "La dieta che inizia il lunedì" },
  { id: 9, text: "Fare finta di non sentire" },
  { id: 10, text: "Un abbonamento a Netflix che nessuno usa" },
  { id: 11, text: "Il bidet" },
  { id: 12, text: "Mangiare la nutella dal barattolo con il cucchiaio" },
  { id: 13, text: "Tre ore di fila alle Poste" },
  { id: 14, text: "Un giro in Vespa senza casco" },
  { id: 15, text: "La partita in TV durante il pranzo di Natale" },
  { id: 16, text: "Il ragù della nonna che cuoce da 6 ore" },
  { id: 17, text: "Un calcio nel sedere" },
  { id: 18, text: "Fare l'amore con le ciabatte ai piedi" },
  { id: 19, text: "Un piatto di pasta al dente" },
  { id: 20, text: "Litigare per il telecomando" },
  { id: 21, text: "Un bacio della zia con il rossetto" },
  { id: 22, text: "Svegliarsi alle 5 di mattina per caso" },
  { id: 23, text: "Il clacson del vicino di casa" },
  { id: 24, text: "Una vacanza in Calabria ad agosto" },
  { id: 25, text: "Riempirsi il piatto e dire che non si mangia molto" },
  { id: 26, text: "Il codice fiscale sbagliato" },
  { id: 27, text: "Un aperitivo che diventa cena" },
  { id: 28, text: "La suocera che arriva senza avvisare" },
  { id: 29, text: "Mentire al medico sui propri vizi" },
  { id: 30, text: "Fare la doccia fredda per sbaglio" },
  { id: 31, text: "Perdere le chiavi di casa" },
  { id: 32, text: "Il mio ex che si è rifatto" },
  { id: 33, text: "Scivolare su una buccia di banana davvero" },
  { id: 34, text: "Spiegare agli anziani come funziona WhatsApp" },
  { id: 35, text: "Il rutto del secolo durante il silenzio assoluto" },
  { id: 36, text: "Scoprire che la tua pizza era senza mozzarella" },
  { id: 37, text: "Un nonno che posta su Instagram" },
  { id: 38, text: "Confondere il deodorante con lo spray per capelli" },
  { id: 39, text: "L'amico che prende sempre il conto e poi sparisce" },
  { id: 40, text: "Il dentista del paese" },
  { id: 41, text: "Trovare i calzini del fidanzato dappertutto" },
  { id: 42, text: "Rispondere a un vocale di 7 minuti" },
  { id: 43, text: "Il jingle di Natale a ottobre" },
  { id: 44, text: "Svegliarsi con il torcicollo il giorno di gala" },
  { id: 45, text: "La moglie che finge di dormire" },
  { id: 46, text: "Un'ora di riunione per decidere cosa mangiare" },
  { id: 47, text: "Il Wi-Fi che va e viene come un'ex" },
  { id: 48, text: "Comprare frutta al mercato e non mangiarla mai" },
  { id: 49, text: "Dimenticare il compleanno della mamma" },
  { id: 50, text: "Il medico di base che dice sempre 'aspettiamo'" },
  { id: 51, text: "Una bottiglia di vino da tre euro" },
  { id: 52, text: "L'IVA del 22% su tutto" },
  { id: 53, text: "Il traffico del venerdì pomeriggio" },
  { id: 54, text: "Scoprire che sei tu il problema" },
  { id: 55, text: "Il papà che mette il volume massimo in macchina" },
  { id: 56, text: "Finire la carta igienica nel momento sbagliato" },
  { id: 57, text: "La pizza senza crosta che si piega" },
  { id: 58, text: "Un gatto che ti ignora" },
  { id: 59, text: "Ricevere il pacco Amazon dal vicino" },
  { id: 60, text: "Un maglione fatto a mano dalla nonna" },
  { id: 61, text: "Litigare sui canali TV con chi ha già visto tutto" },
  { id: 62, text: "Il secondo piatto che arriva quando hai già finito" },
  { id: 63, text: "Un'email con allegato che non si apre" },
  { id: 64, text: "La multa presa fuori casa propria" },
  { id: 65, text: "Dimenticarsi di dire 'grazie' al cassiere" },
  { id: 66, text: "Il cugino di Milano che parla solo di lavoro" },
  { id: 67, text: "Un documento scaduto il giorno prima" },
  { id: 68, text: "La sveglia del telefono che non suona" },
  { id: 69, text: "Trovare il gelato finito nel freezer" },
  { id: 70, text: "Il bagno occupato in momenti critici" },
  { id: 71, text: "Un pisolino di 20 minuti che dura 3 ore" },
  { id: 72, text: "La verdura mascherata nel minestrone" },
  { id: 73, text: "Leggere il contratto dopo aver firmato" },
  { id: 74, text: "Il meme che non fa ridere nessuno" },
  { id: 75, text: "Una pizza con l'ananas" },
  { id: 76, text: "Il condizionatore d'aria al contrario" },
  { id: 77, text: "Trovare un capello nella zuppa" },
  { id: 78, text: "L'autobus che parte 30 secondi prima" },
  { id: 79, text: "Rispondere 'sto bene' quando non è vero" },
  { id: 80, text: "Un applauso a scoppio ritardato" },
  { id: 81, text: "Il vicino che fa ginnastica alle 6:30" },
  { id: 82, text: "Passare il Ferragosto a Milano" },
  { id: 83, text: "Un brindisi senza guardare negli occhi" },
  { id: 84, text: "Scoprire che la bottiglia è vuota" },
  { id: 85, text: "L'amico che arriva sempre con fame" },
  { id: 86, text: "Stappare il vino sbagliato" },
  { id: 87, text: "Il messaggio inviato alla persona sbagliata" },
  { id: 88, text: "Salutare qualcuno che non mi saluta indietro" },
  { id: 89, text: "L'assegno del nonno per Natale" },
  { id: 90, text: "Fare le valige all'ultimo momento" },
  { id: 91, text: "Un brindisi con succo di frutta" },
  { id: 92, text: "La scusa di avere già impegni quando non è vero" },
  { id: 93, text: "Il cameriere che porta il conto senza che lo chieda" },
  { id: 94, text: "Trovare l'unico buco nel calzino" },
  { id: 95, text: "Il cane che abbaia solo di notte" },
  { id: 96, text: "Una risata inaspettata durante il funerale" },
  { id: 97, text: "L'ex che mette 'mi piace' alle tue foto vecchie" },
  { id: 98, text: "Svegliarsi e non ricordare il sogno bellissimo" },
  { id: 99, text: "Il telefonino che muore al 3% di batteria" },
  { id: 100, text: "Una pizza bianca senza condimento" },
  { id: 101, text: "Aspettare il medico per 2 ore" },
  { id: 102, text: "La nipote che fa domande scomode a tavola" },
  { id: 103, text: "Comprare vestiti di una taglia in meno per 'motivarsi'" },
  { id: 104, text: "Un bacio della nonna con la barba" },
  { id: 105, text: "Il treno che non passa mai" },
  { id: 106, text: "Un viaggio in camper con tutta la famiglia" },
  { id: 107, text: "La cugina che porta il fidanzato sconosciuto a cena" },
  { id: 108, text: "Trovare la macchinetta rotta la mattina" },
  { id: 109, text: "Il bagno del bar della stazione" },
  { id: 110, text: "Un aperitivo che dura tutta la notte" },
  { id: 111, text: "Il canto del gallo del vicino" },
  { id: 112, text: "Dimenticare la spesa al supermercato" },
  { id: 113, text: "L'arancino a Milano" },
  { id: 114, text: "Una vacanza che costa più del previsto" },
  { id: 115, text: "Il neonato che piange durante il film" },
  { id: 116, text: "La suocera che critica la cucina" },
  { id: 117, text: "Ballare senza musica al matrimonio" },
  { id: 118, text: "Il compleanno dimenticato del migliore amico" },
  { id: 119, text: "Una tartina con maionese su tutto" },
  { id: 120, text: "La settimana bianca con la famiglia allargata" },
  { id: 121, text: "La pasta scotta in un ristorante stellato" },
  { id: 122, text: "Un regalo riciclato con carta nuova" },
  { id: 123, text: "Il vicino che fischia sempre la stessa canzone" },
  { id: 124, text: "Una conversazione col tassista sulla politica" },
  { id: 125, text: "Il tiramisù di mia zia" },
  { id: 126, text: "La chat di gruppo dei parenti a Natale" },
  { id: 127, text: "Un selfie con Babbo Natale al centro commerciale" },
  { id: 128, text: "Il bucato steso quando inizia a piovere" },
  { id: 129, text: "Un nonno che non sa accendere la TV" },
  { id: 130, text: "La bisnonna che vuole Instagram" },
  { id: 131, text: "Il figlio che chiede il motorino a 14 anni" },
  { id: 132, text: "Un tuffo in mare a febbraio per fare colpo" },
  { id: 133, text: "La mamma che ti chiama 'tesoro' davanti agli amici" },
  { id: 134, text: "Mandare vocali di 10 minuti invece di scrivere" },
  { id: 135, text: "Il cane della vicina che abbaia sempre" },
  { id: 136, text: "Una cena romantica interrotta dal cameriere troppo zelante" },
  { id: 137, text: "Il giochino dello smartphone durante la messa" },
  { id: 138, text: "Scoprire che il latte è scaduto nel caffè" },
  { id: 139, text: "L'amico che porta sempre la birra calda" },
  { id: 140, text: "Dimenticare i nomi dei propri figli" },
  { id: 141, text: "La nonna che spedisce emoji a caso" },
  { id: 142, text: "Un ritardo Trenitalia di 2 ore" },
  { id: 143, text: "Saltare il pranzo e mangiare il doppio a cena" },
  { id: 144, text: "Un tacco rotto durante l'inaugurazione" },
  { id: 145, text: "Il cellulare che cade nella toilet" },
  { id: 146, text: "Litigare per il posto a sedere sul treno" },
  { id: 147, text: "Il gatto che sale sul computer durante la videochiamata" },
  { id: 148, text: "Ricevere un regalo 'pensato ma sbagliato'" },
  { id: 149, text: "La sveglia del vicino più forte della tua" },
  { id: 150, text: "Il kebab delle 3 di notte" },
  { id: 151, text: "La vecchia zia che ti chiede quando ti sposi" },
  { id: 152, text: "Un guasto al condizionatore d'agosto" },
  { id: 153, text: "Il menù senza prezzi" },
  { id: 154, text: "Trovare l'unico taxi senza aria condizionata" },
  { id: 155, text: "Un tramonto visto da soli con i piedi bagnati" },
  { id: 156, text: "La bottiglia di vino già aperta che non si chiude" },
  { id: 157, text: "Il barista che sa già cosa prendi" },
  { id: 158, text: "Una siesta non prevista di 3 ore" },
  { id: 159, text: "Il cugino che porta solo critiche ai pranzi" },
  { id: 160, text: "Un'amica che ti dice 'sei bellissimo/a comunque'" },
  { id: 161, text: "Il giorno dopo la laurea senza sapere cosa fare" },
  { id: 162, text: "Una tartaruga come animale domestico" },
  { id: 163, text: "Il sogno di vincere al gratta e vinci" },
  { id: 164, text: "La birra senza alcol per guidare" },
  { id: 165, text: "Un incontro accidentale con l'ex al supermercato" },
  { id: 166, text: "Il portafoglio trovato con tutti i soldi mancanti" },
  { id: 167, text: "Una puntata di Beautiful che non capisce nessuno" },
  { id: 168, text: "Il vino bianco freddo del venerdì sera" },
  { id: 169, text: "La pizza margherita alle 22:30" },
  { id: 170, text: "Un amico che ti dice 'ho visto il tuo ex, stava bene'" },
  { id: 171, text: "Il lunedì senza caffè" },
  { id: 172, text: "Una nonna con smartphone e tutto" },
  { id: 173, text: "L'abbonamento in palestra che faccio solo a gennaio" },
  { id: 174, text: "Un gatto sul laptop durante il meeting" },
  { id: 175, text: "Il sorpasso in autostrada a 200 all'ora" },
  { id: 176, text: "Un urlo liberatorio nel traffico" },
  { id: 177, text: "Il tifoso che piange quando perde la squadra" },
  { id: 178, text: "Una partita di burraco che finisce alle 2" },
  { id: 179, text: "Il bambino che chiede 'perché' ogni 30 secondi" },
  { id: 180, text: "La zia che porta sempre il pandoro di marca diversa" },
  { id: 181, text: "Un complimento dal postino" },
  { id: 182, text: "Una proposta di matrimonio al McDonald's" },
  { id: 183, text: "Il fidanzato/a che dorme sul divano" },
  { id: 184, text: "La mamma che cucina troppo per uno" },
  { id: 185, text: "Un abbraccio della nonna che stritola" },
  { id: 186, text: "Il vicino che taglia l'erba di domenica mattina" },
  { id: 187, text: "La sveglia disattivata per sbaglio" },
  { id: 188, text: "Un giro al mercato delle pulci" },
  { id: 189, text: "Il nonno che racconta sempre la stessa storia" },
  { id: 190, text: "Una vacanza all'isola d'Elba a Ferragosto" },
  { id: 191, text: "Il fidanzato/a che russa" },
  { id: 192, text: "La coda al pronto soccorso" },
  { id: 193, text: "Un compleanno dimenticato ma ricordato su Facebook" },
  { id: 194, text: "Il migliore amico che porta la ragazza alla festa" },
  { id: 195, text: "Una cassata siciliana a metà febbraio" },
  { id: 196, text: "Il tiramisù fatto con i savoiardi sbagliati" },
  { id: 197, text: "Un regalo di nozze da 50 euro per due" },
  { id: 198, text: "La nonna che ti mette i soldi nel pasto" },
  { id: 199, text: "Un aperol spritz con ghiaccio troppo sciolto" },
  { id: 200, text: "Il ragazzo della pizza che arriva sempre in ritardo" },
  { id: 201, text: "La bolletta del gas a dicembre" },
  { id: 202, text: "Un pasto in aereo che non si capisce cosa sia" },
  { id: 203, text: "Il finestrino del treno che non si chiude" },
  { id: 204, text: "Un caffè decaffeinato di sera" },
  { id: 205, text: "Il vicino di ombrellone rumoroso" },
  { id: 206, text: "La sedia che cigola durante la conferenza" },
  { id: 207, text: "Un compleanno a sorpresa per chi odia le sorprese" },
  { id: 208, text: "Il cappuccino dopo le 11 in un bar romano" },
  { id: 209, text: "La macchina rotta fuori dall'autostrada" },
  { id: 210, text: "Un cane che fa la pipì sul tuo zaino" },
  { id: 211, text: "Il ristorante cinese aperto a Ferragosto" },
  { id: 212, text: "Un bacio sotto la pioggia che finisce con l'influenza" },
  { id: 213, text: "Il dottore che dice 'non si preoccupi' via WhatsApp" },
  { id: 214, text: "Una giornata senza telefono per scommessa" },
  { id: 215, text: "Il bimbo che piange nel carrello" },
  { id: 216, text: "La coda alle Poste il lunedì" },
  { id: 217, text: "Il cellulare che squilla durante il silenzio in chiesa" },
  { id: 218, text: "La nonna che ti chiede se mangi abbastanza" },
  { id: 219, text: "Il parcheggio in doppia fila con le quattro frecce" },
  { id: 220, text: "La macchinetta del caffè rotta in ufficio" },
  { id: 221, text: "Un compleanno senza torta" },
  { id: 222, text: "Il vecchio parrucchiere del quartiere" },
  { id: 223, text: "La cugina che posta tutto su Instagram" },
  { id: 224, text: "Un regalo uguale all'anno scorso" },
  { id: 225, text: "Il collega che parla troppo in riunione" },
  { id: 226, text: "La pasta cotta troppo al dentone" },
  { id: 227, text: "Un pigiama party a 40 anni" },
  { id: 228, text: "Il Wi-Fi che funziona solo in un angolo della casa" },
  { id: 229, text: "La riunione che poteva essere un'email" },
  { id: 230, text: "Un fidanzato/a che dimentica l'anniversario" },
  { id: 231, text: "Il gelato caduto sul marciapiede nuovo" },
  { id: 232, text: "La farmacia chiusa nel momento del bisogno" },
  { id: 233, text: "Il meccanico che trova sempre un altro problema" },
  { id: 234, text: "La zia che porta sempre i dolci sbagliati" },
  { id: 235, text: "Un amico che arriva sempre due ore dopo" },
  { id: 236, text: "Il tassista che prende la strada più lunga" },
  { id: 237, text: "La cena di gala con le scarpe che stringono" },
  { id: 238, text: "Un bacio di mezzanotte rovinato dall'alito" },
  { id: 239, text: "Una chiamata persa da un numero sconosciuto" },
  { id: 240, text: "Il termosifone che non scalda mai abbastanza" },
  { id: 241, text: "La sorpresa di un parente che viene a stare 3 settimane" },
  { id: 242, text: "Un viaggio in autobus di 5 ore in piedi" },
  { id: 243, text: "La password WiFi scritta in caratteri illeggibili" },
  { id: 244, text: "Un compleanno a 18 anni senza la patente ancora" },
  { id: 245, text: "La partita persa all'ultimo minuto" },
  { id: 246, text: "Un lunedì mattina senza motivo per alzarsi" },
  { id: 247, text: "Il nonno che sbaglia sempre il nome dei nipoti" },
  { id: 248, text: "Un esame orale con il professore antipatico" },
  { id: 249, text: "Il giorno in cui dimentichi tutto" },
  { id: 250, text: "La spesa grossa del sabato mattina" },
  { id: 251, text: "Un ballo con qualcuno che non sa ballare" },
  { id: 252, text: "Il caffè freddo per distrazione" },
  { id: 253, text: "La cena di lavoro che dura 4 ore" },
  { id: 254, text: "Un figlio che torna a casa a 30 anni" },
  { id: 255, text: "Il gatto che porta topi morti come regalo" },
  { id: 256, text: "Un piano B che è peggio del piano A" },
  { id: 257, text: "Il collega che ruba il tuo caffè in ufficio" },
  { id: 258, text: "La spiaggia piena a Ferragosto" },
  { id: 259, text: "Un invito a nozze di qualcuno che non conosci bene" },
  { id: 260, text: "Il traffico di ritorno dalle vacanze" },
  { id: 261, text: "La colazione saltata per dormire di più" },
  { id: 262, text: "Il lunedì dopo le vacanze estive" },
  { id: 263, text: "La pizza consegnata fredda" },
  { id: 264, text: "Il deodorante finito durante una giornata importante" },
  { id: 265, text: "La valigia smarrita in aeroporto" },
  { id: 266, text: "Un regalo di laurea che non si usa mai" },
  { id: 267, text: "Il vicino che fa feste ogni weekend" },
  { id: 268, text: "Un bacio dato per sbaglio alla persona sbagliata" },
  { id: 269, text: "Il semaforo rosso sempre al momento sbagliato" },
  { id: 270, text: "Un compleanno passato in ufficio a lavorare" },
  { id: 271, text: "Il cane che mangia le scarpe" },
  { id: 272, text: "La valigia oversize che non entra in bagagliaio" },
  { id: 273, text: "Un invito a nozze in agosto a Palermo" },
  { id: 274, text: "Il caffè che cade sul vestito bianco" },
  { id: 275, text: "La nonna che ti manda le foto di gatti" },
  { id: 276, text: "Un ritiro spirituale invece di una vacanza" },
  { id: 277, text: "Il nonno che vuole insegnarti a pescare" },
  { id: 278, text: "La lista delle cose da fare che si allunga sempre" },
  { id: 279, text: "Un litigio per un posto al sole in spiaggia" },
  { id: 280, text: "Il gatto che si siede sulla tastiera" },
  { id: 281, text: "Un regalo di Natale ancora imballato ad aprile" },
  { id: 282, text: "Il dottore che si dimentica di te in sala d'attesa" },
  { id: 283, text: "Un weekend in montagna senza neve" },
  { id: 284, text: "La suocera che confronta sempre con la sua cucina" },
  { id: 285, text: "Un viaggio organizzato last minute" },
  { id: 286, text: "Il bar chiuso il lunedì" },
  { id: 287, text: "La nonna che scrive tutto in maiuscolo su WhatsApp" },
  { id: 288, text: "Un complimento sul tuo italiano da un italiano" },
  { id: 289, text: "Il gelato al pistacchio senza pistacchi" },
  { id: 290, text: "La serata romantica rovinata da un film horror" },
  { id: 291, text: "Un parente che porta il cane non invitato" },
  { id: 292, text: "Il parrucchiere che ti taglia più di quanto vuoi" },
  { id: 293, text: "Un viaggio in treno accanto a chi parla forte al telefono" },
  { id: 294, text: "Il vicino di casa che ti prende la posta" },
  { id: 295, text: "Un segreto che non regge nemmeno un giorno" },
  { id: 296, text: "Il bambino che chiede perché i grandi bevono caffè" },
  { id: 297, text: "La serata al cinema con il film sbagliato" },
  { id: 298, text: "Un pranzo di Natale dalle 13 alle 18" },
  { id: 299, text: "La cassetta delle lettere piena di pubblicità" },
  { id: 300, text: "Il gatto che porta un uccellino morto come regalo" },
  { id: 301, text: "La pizza in scatola invece di quella vera" },
  { id: 302, text: "Un tramonto visto da soli con il telefono scarico" },
  { id: 303, text: "Il barista che fa il caffè troppo lungo" },
  { id: 304, text: "La torta di compleanno bruciata" },
  { id: 305, text: "Un messaggio di auguri generico copiato" },
  { id: 306, text: "Il neonato che urla durante tutta la messa" },
  { id: 307, text: "La nonna che ti chiede ogni volta se hai mangiato" },
  { id: 308, text: "Un lavoro che non sai spiegare ai parenti" },
  { id: 309, text: "Il parcheggio multato per cinque minuti" },
  { id: 310, text: "Una cena senza vino" },
  { id: 311, text: "Un weekend lungo senza uscire di casa" },
  { id: 312, text: "Il collega che porta il pesce in ufficio a pranzo" },
  { id: 313, text: "La chat di gruppo che non riesci a silenziare" },
  { id: 314, text: "Il limone dell'aperitivo che schizza nell'occhio" },
  { id: 315, text: "La moglie/marito che finge di dormire quando il bimbo piange" },
  { id: 316, text: "Un compleanno dimenticato e recuperato con post tardivo" },
  { id: 317, text: "La borsa della spesa che si rompe davanti al supermercato" },
  { id: 318, text: "Un film di 3 ore senza pause" },
  { id: 319, text: "Il Wi-Fi del bar che non funziona mai" },
  { id: 320, text: "Un aperol spritz a colazione" },
  { id: 321, text: "Il vicino che parcheggia davanti al cancello" },
  { id: 322, text: "La mamma che chiama sempre al momento sbagliato" },
  { id: 323, text: "Il caffè con troppo zucchero" },
  { id: 324, text: "La vasca da bagno riempita ma poi non usata" },
  { id: 325, text: "Il nonno che guarda le telenovelas" },
  { id: 326, text: "Un amico che vuole dividere il conto al centesimo" },
  { id: 327, text: "Il jeans che si stringe dopo Natale" },
  { id: 328, text: "Un weekend in b&b con letto che cigola" },
  { id: 329, text: "Il gatto che miagola alle 4 di mattina" },
  { id: 330, text: "La signora al supermercato che paga in monetine" },
  { id: 331, text: "Un panettone ricevuto a febbraio" },
  { id: 332, text: "La valigia che non chiude mai bene" },
  { id: 333, text: "Il collega che commenta tutto quello che fai" },
  { id: 334, text: "La torta di compleanno con 40 candeline" },
  { id: 335, text: "Un viaggio in aereo con scala di 8 ore" },
  { id: 336, text: "Il gelato mangiato di nascosto" },
  { id: 337, text: "Un selfie con la famiglia allargata che va sempre male" },
  { id: 338, text: "Il cane che porta a spasso il padrone" },
  { id: 339, text: "La bolletta del condominio con spese extra" },
  { id: 340, text: "Il pesce d'aprile riuscito a metà" },
  { id: 341, text: "La nonna che dice che cucinava meglio lei" },
  { id: 342, text: "Un ballo di fine anno che ricordi per sempre" },
  { id: 343, text: "Il gatto che vuole uscire appena lo fai rientrare" },
  { id: 344, text: "Un pomeriggio d'agosto senza corrente" },
  { id: 345, text: "Il collega in smart working che dimentica la telecamera" },
  { id: 346, text: "La sveglia messa per le 6:00 invece delle 7:00" },
  { id: 347, text: "Il condizionatore dell'ufficio che congela le mani" },
  { id: 348, text: "La pasta al forno riscaldata il giorno dopo" },
  { id: 349, text: "Un regalo improvvisato con quello che c'è in casa" },
  { id: 350, text: "Il bambino che trova la lista di Babbo Natale" },
  { id: 351, text: "La zia che regala sempre calendari" },
  { id: 352, text: "Un drink analcolico in discoteca" },
  { id: 353, text: "Il gatto che si mette sempre davanti allo schermo" },
  { id: 354, text: "Un incontro di lavoro in costume da bagno" },
  { id: 355, text: "Il nonno che mette la TV a tutto volume" },
  { id: 356, text: "La partita di calcetto che finisce in rissa amichevole" },
  { id: 357, text: "Un pranzo veloce che dura 3 ore" },
  { id: 358, text: "Il messaggio di auguri spedito alla persona sbagliata" },
  { id: 359, text: "La festa di laurea che finisce alle 6 di mattina" },
  { id: 360, text: "Il bagnino che dorme al sole" },
  { id: 361, text: "La sposa che arriva in ritardo di un'ora" },
  { id: 362, text: "Un weekend di pioggia in campagna" },
  { id: 363, text: "Il cameriere che porta il conto prima che tu finisca" },
  { id: 364, text: "La macchina nuova che si graffia il primo giorno" },
  { id: 365, text: "Il piatto vuoto lasciato nel lavandino" },
  { id: 366, text: "La cena romantica con bambino che piange in sottofondo" },
  { id: 367, text: "Un nonno che non capisce lo streaming" },
  { id: 368, text: "Il cane che mangia le scarpe del fidanzato" },
  { id: 369, text: "Un compleanno in quarantena" },
  { id: 370, text: "Il gatto che beve il tuo latte" },
  { id: 371, text: "La bolletta arretrata del 2015" },
  { id: 372, text: "Un aperitivo con il cugino di cui non si ricorda il nome" },
  { id: 373, text: "Il vicino che fa i lavori di domenica" },
  { id: 374, text: "Un piatto di spaghetti alla carbonara senza guanciale" },
  { id: 375, text: "Il professore che interroga sempre te" },
  { id: 376, text: "Un collega che risponde 'ci penso' a tutto" },
  { id: 377, text: "Il nonno che ti chiede perché non sei ancora sposato" },
  { id: 378, text: "La torta fatta in casa che non lievita" },
  { id: 379, text: "Il gatto che porta in dono un calzino" },
  { id: 380, text: "La cugina che arriva sempre con il fidanzato nuovo" },
  { id: 381, text: "Un lungo messaggio letto solo a metà" },
  { id: 382, text: "Il corso di yoga che dura 5 minuti al giorno" },
  { id: 383, text: "La nonna che fa 20 domande sull'app di incontri" },
  { id: 384, text: "Il maglione di lana della nonna" },
  { id: 385, text: "Un pranzo domenicale che si prolunga fino a cena" },
  { id: 386, text: "Il vecchio motorino del paese che ancora funziona" },
  { id: 387, text: "Un invito di matrimonio per la cerimonia alle 7 di mattina" },
  { id: 388, text: "La partita di calcio che finisce 0-0" },
  { id: 389, text: "Il medico che dice 'male non fa'" },
  { id: 390, text: "La suocera che porta sempre troppo cibo" },
  { id: 391, text: "Il nonno che usa WhatsApp per la prima volta" },
  { id: 392, text: "Un bacio ricevuto dalla nonna baffuta" },
  { id: 393, text: "Il collega che manda mail alle 23:00" },
  { id: 394, text: "Il barbiere che parla sempre del calcio" },
  { id: 395, text: "Il vicino di spiaggia con la radio" },
  { id: 396, text: "La notte prima dell'esame" },
  { id: 397, text: "Un compleanno da solo con Netflix" },
  { id: 398, text: "Il gatto che beve dal vaso dei fiori" },
  { id: 399, text: "Il barman che fa il mojito sbagliato" },
  { id: 400, text: "La torta nuziale che si rompe" },
  { id: 401, text: "Il collega che finisce il caffè e non rifà" },
  { id: 402, text: "La valigia che arriva a destinazione senza di te" },
  { id: 403, text: "Un litigio con il GPS" },
  { id: 404, text: "Il cane che porta la palla ma non la molla" },
  { id: 405, text: "Un allarme del vicino che suona tutta la notte" },
  { id: 406, text: "Il gelato finito prima che tu arrivi" },
  { id: 407, text: "Un pranzo senza pane" },
  { id: 408, text: "Il nonno che si addormenta sul divano alle 8" },
  { id: 409, text: "La zia che porta 10 kg di cibo per fermarsi un'ora" },
  { id: 410, text: "Il gatto che ti sveglia alle 5 con le fusa" },
  { id: 411, text: "La pasta cucinata per l'ospite che cancella all'ultimo" },
  { id: 412, text: "Il detersivo finito a metà lavaggio" },
  { id: 413, text: "Un viaggio di 6 ore in macchina senza musica" },
  { id: 414, text: "Il messaggio vocale di 8 minuti senza senso" },
  { id: 415, text: "La famiglia riunita solo per Natale e Pasqua" },
  { id: 416, text: "Un party senza musica" },
  { id: 417, text: "Il semaforo pedonale che scatta subito a rosso" },
  { id: 418, text: "Un compleanno in hotel con minibar vuoto" },
  { id: 419, text: "La pizza in scatola riscaldata nel microonde" },
  { id: 420, text: "Il tifoso che festeggia nel posto sbagliato" },
  { id: 421, text: "Un gatto che ronfa sul giornale" },
  { id: 422, text: "La multa scaduta da pagare 10 anni dopo" },
  { id: 423, text: "Un bagnetto nei Navigli" },
  { id: 424, text: "Il pigiama indossato tutto il weekend" },
  { id: 425, text: "Un selfie con la mascherina ancora sul mento" },
  { id: 426, text: "La pizza ordinata per tutti che non va bene a nessuno" },
  { id: 427, text: "Il confetto di nozze da 10 anni fa in fondo alla borsa" },
  { id: 428, text: "Un nonno che non sa cos'è Spotify" },
  { id: 429, text: "La sorella che ti prende le cose senza chiedere" },
  { id: 430, text: "Il papà che fa il check-in in aeroporto con 6 ore di anticipo" },
  { id: 431, text: "Una serata 'tranquilla' che finisce a ballare sul tavolo" },
  { id: 432, text: "Il cuoco del ristorante che si offende se non finisci il piatto" },
  { id: 433, text: "Un cappuccino ghiacciato in dicembre" },
  { id: 434, text: "Il figlio che non risponde ai messaggi ma è online" },
  { id: 435, text: "Una cena con la squadra di calcio del figlio" },
  { id: 436, text: "Il posteggiatore abusivo a Napoli" },
  { id: 437, text: "Una gita in pullman con la scuola" },
  { id: 438, text: "Il professore che non risponde alle email" },
  { id: 439, text: "Un gelato ai tre gusti che si scioglie subito" },
  { id: 440, text: "La partita al videogioco con il nipote che ti batte" },
  { id: 441, text: "Il vicino che accende il barbecue sotto la tua finestra" },
  { id: 442, text: "Un compleanno con la torta sbagliata" },
  { id: 443, text: "La sveglia domenicale del campanile" },
  { id: 444, text: "Il collega che porta il cane in ufficio" },
  { id: 445, text: "Un aperitivo di 'soli 30 minuti' che dura 4 ore" },
  { id: 446, text: "Il momento in cui realizzi che hai perso il treno" },
  { id: 447, text: "La conferenza Zoom in cui non riesci a disattivare il microfono" },
  { id: 448, text: "Un nonno che usa il tablet come tavolino" },
  { id: 449, text: "La ricevuta dello scontrino lunga quanto il braccio" },
  { id: 450, text: "Il momento in cui la pizza è finita ma hai ancora fame" },
  { id: 451, text: "Un'estate intera a guardare serie TV" },
  { id: 452, text: "Il bambino che rompe il silenzio in un posto sbagliato" },
  { id: 453, text: "La mamma che segue ancora il telegiornale delle 13:30" },
  { id: 454, text: "Un biglietto aereo comprato e mai usato" },
  { id: 455, text: "Il cugino americano che arriva e non capisce niente" },
  { id: 456, text: "Una notte di Capodanno in casa a guardare l'orologio" },
  { id: 457, text: "Il gatto che porta via il panino dal piatto" },
  { id: 458, text: "Un corso di cucina per principianti quando sai già cucinare" },
  { id: 459, text: "La zia che porta sempre la stessa insalata russa" },
  { id: 460, text: "Il momento in cui scopri che c'è la coda dal medico" },
  { id: 461, text: "Un gelato al gusto di risotto milanese" },
  { id: 462, text: "Il nonno che spegne le luci mentre sei in bagno" },
  { id: 463, text: "Una bolletta della luce in estate con il condizionatore" },
  { id: 464, text: "Il fidanzato che tifa la squadra avversaria" },
  { id: 465, text: "Un pranzo in cui la conversazione è solo di malattie" },
  { id: 466, text: "La pasta e fagioli di mia nonna (non quella di tua nonna)" },
  { id: 467, text: "Un film con il protagonista che non ti piace" },
  { id: 468, text: "Il momento in cui il telefono cade nel water" },
  { id: 469, text: "Una spiegazione di 20 minuti per qualcosa di semplice" },
  { id: 470, text: "Il gatto che ti guarda mentre mangi e non ti lascia in pace" },
  { id: 471, text: "Un invito a correre la maratona come regalo di compleanno" },
  { id: 472, text: "La sagra del paese con la pioggia" },
  { id: 473, text: "Un nonno che vuole insegnarti a giocare a briscola" },
  { id: 474, text: "Il momento in cui realizzi di aver dimenticato il portafoglio" },
  { id: 475, text: "Una cena vegana in una trattoria tradizionale" },
  { id: 476, text: "Il collega che mette il telefono in viva voce in ufficio" },
  { id: 477, text: "Un weekend al mare con temporale dal venerdì" },
  { id: 478, text: "La nonna che ti insegna ancora a fare le faccende" },
  { id: 479, text: "Il momento in cui il caffè macchia la camicia bianca" },
  { id: 480, text: "Un aperitivo dove conosci solo l'organizzatore" },
  { id: 481, text: "La pizza che arriva quando hai già mangiato i cracker" },
  { id: 482, text: "Il vicino di aereo che occupa il bracciolo" },
  { id: 483, text: "Un compleanno a sorpresa che sai già da settimane" },
  { id: 484, text: "Il momento in cui il GPS dice 'svolta a destra' in autostrada" },
  { id: 485, text: "Una passeggiata al parco con 40 gradi" },
  { id: 486, text: "Il gatto che viene a fare le fusa solo quando sei di corsa" },
  { id: 487, text: "Un lunedì mattina con tutti i semafori rossi" },
  { id: 488, text: "La suocera che riassetta casa tua senza dirlo" },
  { id: 489, text: "Un gelato mangiato di fretta sotto il sole" },
  { id: 490, text: "Il momento in cui finisce il caffè e il bar è chiuso" },
  { id: 491, text: "Una gita fuori porta che diventa un'avventura di sopravvivenza" },
  { id: 492, text: "Il collega che risponde sempre 'in CC a tutti'" },
  { id: 493, text: "Un nonno che chiama ogni app 'il computer'" },
  { id: 494, text: "La moglie/marito che dice 'non importa' e invece importa" },
  { id: 495, text: "Un week-end di relax che diventa una lista di commissioni" },
  { id: 496, text: "Il momento in cui il bimbo si sveglia appena ti siedi sul divano" },
  { id: 497, text: "Una dieta che inizia dopo il cornetto" },
  { id: 498, text: "Il cane che abbaia solo quando parli al telefono" },
  { id: 499, text: "Un compleanno in cui ti regalano tutti la stessa cosa" },
  { id: 500, text: "Il momento in cui il Wi-Fi cade durante una videochiamata importante" },
]

export function shuffleArray<T>(array: T[]): T[] {
  const arr = [...array]
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr
}

export function getAnswerById(id: number): AnswerCard | undefined {
  return ANSWERS.find(a => a.id === id)
}

export function getQuestionById(id: number): QuestionCard | undefined {
  return QUESTIONS.find(q => q.id === id)
}
