import type { QuestionCard, AnswerCard } from '@/types/game'

export const QUESTIONS: QuestionCard[] = [
  { id: 1, text: "La cosa che fai subito dopo il sesso ma non ammetteresti mai è ___" },
  { id: 2, text: "Il modo peggiore per scoprire che il tuo partner ti tradisce è ___" },
  { id: 3, text: "Cosa non dovresti mai mandare per messaggio all'ex? ___" },
  { id: 4, text: "Il segreto per mantenere vivo il desiderio dopo 10 anni insieme è ___" },
  { id: 5, text: "La cosa più italiana da fare durante il sesso è ___" },
  { id: 6, text: "Il momento peggiore per scoprire di non avere i preservativi è ___" },
  { id: 7, text: "Cosa cambia nella vita sessuale dopo i 40 anni? ___" },
  { id: 8, text: "Il regalo più inappropriato da fare alla suocera è ___" },
  { id: 9, text: "Come si sopravvive a Natale sapendo che i tuoi genitori fanno ancora sesso? ___" },
  { id: 10, text: "La cosa più imbarazzante che può capitare durante il sesso è ___" },
  { id: 11, text: "Il problema principale degli italiani a letto è ___" },
  { id: 12, text: "Cosa fa un italiano quando il partner non ha voglia? ___" },
  { id: 13, text: "Il modo migliore per portarsi a casa qualcuno al bar è ___" },
  { id: 14, text: "Il rimedio della nonna per il calo del desiderio è ___" },
  { id: 15, text: "La cosa che un italiano fa meglio di tutti in camera da letto è ___" },
  { id: 16, text: "Come si riconosce qualcuno che non fa sesso da troppo tempo? ___" },
  { id: 17, text: "Il momento peggiore per chiamare la mamma è ___" },
  { id: 18, text: "Come ci si prepara per una notte che non si dimentica? ___" },
  { id: 19, text: "Cosa non può mai mancare nel cassetto del comodino? ___" },
  { id: 20, text: "Il lavoro più utile dopo una relazione finita male è ___" },
  { id: 21, text: "Come si convincono i suoceri che sei la persona giusta senza mentire troppo? ___" },
  { id: 22, text: "La cosa più difficile da spiegare al partner dopo una notte fuori è ___" },
  { id: 23, text: "Perché le mamme italiane sanno sempre quando hai fatto sesso? ___" },
  { id: 24, text: "Il momento in cui capisci che la storia è finita davvero è ___" },
  { id: 25, text: "Cosa fa un uomo italiano di 60 anni quando scopre Tinder? ___" },
  { id: 26, text: "Il modo peggiore per iniziare un'avventura di una notte è ___" },
  { id: 27, text: "La scusa migliore per tornare a casa alle 7 di mattina è ___" },
  { id: 28, text: "Cosa succede quando il partner scopre la tua cronologia del browser? ___" },
  { id: 29, text: "Come si trova un appuntamento decente a Roma? ___" },
  { id: 30, text: "La cosa più assurda che fa un italiano per conquistare qualcuno all'estero è ___" },
  { id: 31, text: "Il modo migliore per evitare il sesso nel periodo di crisi di coppia è ___" },
  { id: 32, text: "Perché gli italiani credono di essere i migliori amanti del mondo? ___" },
  { id: 33, text: "La peggiore giustificazione per non avere voglia è ___" },
  { id: 34, text: "Cosa succede se dici a un italiano che il suo modo di fare l'amore è noioso? ___" },
  { id: 35, text: "Il momento più eccitante della settimana in una coppia di lunga data è ___" },
  { id: 36, text: "Come si capisce che qualcuno vuole portarti a letto senza dirlo? ___" },
  { id: 37, text: "Il peggior complimento che puoi fare a qualcuno a letto è ___" },
  { id: 38, text: "Cosa fa un politico italiano quando viene beccato con l'amante? ___" },
  { id: 39, text: "Il rimedio universale per rimettere pepe in una relazione è ___" },
  { id: 40, text: "La cosa più strana trovata nel comodino di un nuovo partner è ___" },
  { id: 41, text: "Perché è impossibile mantenere una relazione a distanza per più di sei mesi? ___" },
  { id: 42, text: "Il modo più veloce per far finire una serata romantica nel peggiore dei modi è ___" },
  { id: 43, text: "Cosa non si fa mai in un hotel quando le pareti sono sottili? ___" },
  { id: 44, text: "Il peggior regalo da fare a un partner nel giorno del vostro anniversario è ___" },
  { id: 45, text: "Come si riconosce qualcuno che è bravo a letto prima ancora di andarci? ___" },
  { id: 46, text: "La cosa che fa calare il desiderio più in fretta è ___" },
  { id: 47, text: "Cosa pensa veramente il gatto quando entrate in camera e chiudete la porta? ___" },
  { id: 48, text: "Il modo più sicuro per perdere un amico è ___" },
  { id: 49, text: "Come si rompe il ghiaccio con qualcuno di molto attraente che non conosci? ___" },
  { id: 50, text: "Il modo più imbarazzante per fare una proposta di matrimonio è ___" },
  { id: 51, text: "La cosa peggiore che può succedere durante una serata hot è ___" },
  { id: 52, text: "Come si convince il partner a provare qualcosa di nuovo a letto? ___" },
  { id: 53, text: "Cosa succede quando il nonno scopre cos'è OnlyFans? ___" },
  { id: 54, text: "La migliore scusa per non dormire a casa propria è ___" },
  { id: 55, text: "Il peggior consiglio sessuale che si possa dare a qualcuno è ___" },
  { id: 56, text: "Come si diventa famosi in Italia senza talento ma con molto altro? ___" },
  { id: 57, text: "La cosa più noiosa che un partner possa fare a letto è ___" },
  { id: 58, text: "Cosa succede in Italia tra le 14:00 e le 16:00 mentre tutti fingono di dormire? ___" },
  { id: 59, text: "Il peggior compagno di vacanza romantica è ___" },
  { id: 60, text: "Come si reagisce quando mandi un nudo alla persona sbagliata? ___" },
  { id: 61, text: "Cosa fa un italiano bloccato in casa con il partner per tre settimane? ___" },
  { id: 62, text: "Il modo più efficace per rovinare una serata che stava andando benissimo è ___" },
  { id: 63, text: "Come fai a capire che sei invecchiato/a sessualmente? ___" },
  { id: 64, text: "La cosa più pericolosa da fare quando sei ubriaco/a e hai il telefono in mano è ___" },
  { id: 65, text: "Cosa fa il nonno quando trova il profilo Instagram della nipote con le foto in bikini? ___" },
  { id: 66, text: "Il modo più creativo per essere licenziato/a dopo una notte con il/la collega è ___" },
  { id: 67, text: "Come si rovina un pranzo domenicale con la famiglia rivelando qualcosa di troppo? ___" },
  { id: 68, text: "La scusa migliore per non fare sesso il mercoledì sera è ___" },
  { id: 69, text: "Cosa succede al primo appuntamento quando ti rendi conto che è bellissimo/a ma noioso/a? ___" },
  { id: 70, text: "Il modo peggiore per fare bella figura con i suoceri nel primo weekend insieme è ___" },
  { id: 71, text: "La cosa più stupida che si fa per conquistare qualcuno è ___" },
  { id: 72, text: "Cosa pensa il cane quando i padroni litigano per colpa del sesso? ___" },
  { id: 73, text: "Il segreto per mantenere una relazione appassionante dopo i primi tre mesi è ___" },
  { id: 74, text: "La cosa che tutti fanno da soli ma nessuno ammette mai è ___" },
  { id: 75, text: "Cosa succede se proponi al partner una fantasia che lui/lei non si aspettava? ___" },
  { id: 76, text: "Il modo più creativo per vendicarsi di un ex che ti ha tradito è ___" },
  { id: 77, text: "Come si reagisce quando scopri che il vicino ti sente attraverso il muro? ___" },
  { id: 78, text: "La cosa più drammatica che può capitare durante una vacanza romantica è ___" },
  { id: 79, text: "Cosa fa un italiano quando incontra qualcuno di bellissimo in vacanza all'estero? ___" },
  { id: 80, text: "Il peggior modo per iniziare una relazione con un/a collega è ___" },
  { id: 81, text: "Come si sopravvive a una notte in treno accanto a qualcuno di attraente che russa? ___" },
  { id: 82, text: "La cosa più bella del sesso con la persona giusta è ___" },
  { id: 83, text: "Come si conquistano i genitori del/la fidanzato/a quando sai che sanno già tutto? ___" },
  { id: 84, text: "Il modo migliore per iniziare il lunedì mattina dopo un weekend di fuoco è ___" },
  { id: 85, text: "Cosa ti fa capire definitivamente che una relazione è finita? ___" },
  { id: 86, text: "Il peggior momento per dire 'ti amo' per la prima volta è ___" },
  { id: 87, text: "Come si reagisce quando l'ex si rifà e diventa irresistibile? ___" },
  { id: 88, text: "La cosa che nessun italiano ammetterà mai di fare da solo/a è ___" },
  { id: 89, text: "Il modo migliore per far sì che una storia di una notte non diventi un problema è ___" },
  { id: 90, text: "Cosa succede quando porti a casa qualcuno e il coinquilino è ancora sveglio? ___" },
  { id: 91, text: "Il peggior modo per chiedere al partner di provare qualcosa di nuovo è ___" },
  { id: 92, text: "Come si fa a sembrare esperti a letto anche quando non lo si è? ___" },
  { id: 93, text: "La cosa che manda più in crisi un italiano dopo i 35 anni è ___" },
  { id: 94, text: "Il modo più italiano per rimediare dopo una figuraccia in camera da letto è ___" },
  { id: 95, text: "Cosa fa davvero paura a un uomo italiano di mezza età? ___" },
  { id: 96, text: "Come si capisce se sei al Sud o al Nord dall'approccio al sesso? ___" },
  { id: 97, text: "La cosa peggiore da dire durante una lite di coppia alle 3 di notte è ___" },
  { id: 98, text: "Il modo più creativo per spiegare alla mamma perché non sei tornato/a a dormire è ___" },
  { id: 99, text: "Cosa succede la mattina dopo una notte di sesso con qualcuno che rivedrai in ufficio? ___" },
  { id: 100, text: "Il segreto per essere sempre desiderati è ___" },
]

export const ANSWERS: AnswerCard[] = [
  // ── Sesso ─────────────────────────────────────────────────────────────────
  { id: 1, text: "Un pompino silenzioso mentre la suocera è in soggiorno" },
  { id: 2, text: "Il cazzo storto che però ci azzecca sempre" },
  { id: 3, text: "Venire prima ancora di togliersi i pantaloni" },
  { id: 4, text: "Il preservativo che si rompe sul più bello" },
  { id: 5, text: "Fare l'orgasmo finto così bene da meritare il David di Donatello" },
  { id: 6, text: "Scopare di nascosto mentre i figli guardano i cartoni" },
  { id: 7, text: "Il vibratore trovato dalla mamma nei bagagli a mano" },
  { id: 8, text: "Mandare la foto del cazzo al gruppo di famiglia per sbaglio" },
  { id: 9, text: "Il peluche che cadeva dal letto ogni volta e interrompeva tutto" },
  { id: 10, text: "Leccare qualcosa che non dovresti e scoprire che ti piace" },
  { id: 11, text: "Il sesso in macchina con il cambio del manuale in posti strategici" },
  { id: 12, text: "Fare sesso a Natale mentre il presepe ti guarda fisso" },
  { id: 13, text: "L'erezione imbarazzante sul bus di linea alle 8 di mattina" },
  { id: 14, text: "Il clistere che nessuno aveva chiesto ma qualcuno ha apprezzato" },
  { id: 15, text: "Scoprire durante il sesso che il letto non è vostro" },
  { id: 16, text: "La posizione che sembrava fattibile su YouTube ma non lo è" },
  { id: 17, text: "Il pene disegnato sulla fronte del ubriaco con il pennarello" },
  { id: 18, text: "Fare sesso anale e poi non sedersi per tre giorni" },
  { id: 19, text: "Il dildo dimenticato sul tavolo quando arriva la pizzeria" },
  { id: 20, text: "Venire troppo presto e far finta che fosse un finire artistico" },
  // ── Peti ──────────────────────────────────────────────────────────────────
  { id: 21, text: "Il peto durante il sesso che spegne tutto come un interruttore" },
  { id: 22, text: "Il peto in yoga così forte che la professoressa si ferma" },
  { id: 23, text: "Il peto trattenuto per due ore durante la cena con i suoceri" },
  { id: 24, text: "Il peto vaginal accidentale che trasforma tutto in imbarazzo cosmico" },
  { id: 25, text: "Il peto nella vasca da bagno che torna su come una mina" },
  { id: 26, text: "Il peto in ascensore con il capo ufficio e due colleghi" },
  { id: 27, text: "Il peto silenziossimo ma letale all'IKEA che spopola il reparto cucine" },
  { id: 28, text: "Il peto al funerale che fa ridere solo te" },
  { id: 29, text: "Il peto durante il cunnilingus che crea un vortice inaspettato" },
  { id: 30, text: "Il peto della nonna al pranzo di Pasqua attribuito al cane" },
  { id: 31, text: "Il peto mattutino del partner che ti sveglia prima della sveglia" },
  { id: 32, text: "Il peto durante la colonscopia che imbarazza il medico" },
  { id: 33, text: "Il peto in piscina che sale in superficie come un testimonial" },
  { id: 34, text: "Il peto che sentono tutti ma tutti fingono di non aver sentito" },
  { id: 35, text: "Il peto a letto che solleva il piumone come un paracadute" },
  // ── Erezioni ─────────────────────────────────────────────────────────────
  { id: 36, text: "L'erezione mattutina che sfonda il pigiama come un tende-tendone" },
  { id: 37, text: "L'erezione durante la messa di prima comunione del nipote" },
  { id: 38, text: "L'erezione al colloquio di lavoro causata dalla stretta di mano" },
  { id: 39, text: "L'erezione che non va via dopo il giro in bicicletta" },
  { id: 40, text: "L'erezione spontanea guardando un documentario sulle balene" },
  { id: 41, text: "L'erezione nella piscina comunale che tutti vedono tranne l'arbitro" },
  { id: 42, text: "L'erezione da Viagra alle 3 di notte quando lei dorme già" },
  { id: 43, text: "L'erezione tradita dai pantaloni della tuta al supermercato" },
  { id: 44, text: "L'erezione da professore spiegata come 'reazione medica al gessetto'" },
  { id: 45, text: "L'erezione a 70 anni che fa più effetto di qualsiasi regalo" },
  // ── Ciclo mestruale ───────────────────────────────────────────────────────
  { id: 46, text: "Il ciclo arrivato durante la notte di nozze — con sindrome da carnevale" },
  { id: 47, text: "Il ciclo così abbondante da mettere in pericolo il materasso bianco dell'hotel" },
  { id: 48, text: "Il ciclo in ritardo di tre settimane e il partner che conta i giorni" },
  { id: 49, text: "Il dolore da ciclo spiegato come 'un po' di mal di pancia' al fidanzato" },
  { id: 50, text: "Il tampone dimenticato dentro per tre giorni trovato in condizioni epiche" },
  { id: 51, text: "Il ciclo che arriva in spiaggia con il costume bianco appena comprato" },
  { id: 52, text: "Il ciclo irregolare che spaventa tutti tranne il ginecologo" },
  { id: 53, text: "Il sesso durante il ciclo — chi lo nega lo ha già fatto" },
  { id: 54, text: "Il PMS che trasforma una ragazza normale in un'entità soprannaturale" },
  { id: 55, text: "Il ciclo usato come scusa per 14 giorni consecutivi di 'stasera no'" },
  { id: 56, text: "Il ciclo sincronizzato con tutte le coinquiline — casa inagibile per 5 giorni" },
  { id: 57, text: "La crisi di pianto da ciclo per uno spot della Mulino Bianco" },
  { id: 58, text: "Il ciclo abbondante che richiede il doppio strato e la preghiera" },
  { id: 59, text: "Il sangue del ciclo trovato nei posti più improbabili del bagno" },
  { id: 60, text: "Il ciclo annunciato dai crampi alle 3 di notte con urla da film horror" },
  // ── Sbronze ──────────────────────────────────────────────────────────────
  { id: 61, text: "La sbronza che ti fa svegliare in un letto sconosciuto con qualcuno sconosciuto" },
  { id: 62, text: "La sbronza che ti convince di saper cantare come Bocelli" },
  { id: 63, text: "La sbronza di Capodanno che finisce con un pianto di 40 minuti sul gabinetto" },
  { id: 64, text: "La sbronza che ti fa fare la proposta di matrimonio a qualcuno conosciuto 3 ore prima" },
  { id: 65, text: "La sbronza con il vino della nonna che ti azzera la memoria da giovedì a domenica" },
  { id: 66, text: "La sbronza che ti porta a chiamare il tuo ex alle 4:23 dicendo 'ti ho sempre amato'" },
  { id: 67, text: "La sbronza con la sambuca che ti fa ballare il liscio davanti a 200 persone" },
  { id: 68, text: "La sbronza di birra che trasforma il bagno in un campo di battaglia" },
  { id: 69, text: "La sbronza di Ferragosto che rivela segreti che non puoi riprendere" },
  { id: 70, text: "La sbronza che finisce con il cesso abbracciato come un fidanzato fidato" },
  { id: 71, text: "La sbronza di prosecco del veneto: inizia a colazione, finisce a mezzanotte" },
  { id: 72, text: "La sbronza che porta a tatuarsi il nome di qualcuno al primo appuntamento" },
  { id: 73, text: "La sbronza da aperol che convince tutti di parlare inglese fluentemente" },
  { id: 74, text: "La sbronza che ti fa credere di avere ancora 22 anni — sino alle 9 del mattino" },
  { id: 75, text: "La sbronza che si scopre fotografata da 40 angoli su TikTok" },
  // ── Famiglia imbarazzante ─────────────────────────────────────────────────
  { id: 76, text: "Il padre che trova i preservativi nel comodino e dice 'bravo figliolo'" },
  { id: 77, text: "La mamma che sente tutto dalla camera accanto e la mattina serve il caffè in silenzio" },
  { id: 78, text: "Il fratello che entra senza bussare nel momento peggiore dell'anno" },
  { id: 79, text: "Il nonno che racconta la prima volta con i dettagli a tavola a Natale" },
  { id: 80, text: "La nonna che trova il vibratore e chiede se è per il collo" },
  { id: 81, text: "Lo zio ubriaco al matrimonio che rivela il segreto di famiglia di 30 anni" },
  { id: 82, text: "La suocera che lava i tuoi slip con le sue mani con aria di superiorità" },
  { id: 83, text: "Il cugino che ti manda la sua storia Instagram dal bagno — con foto non richieste" },
  { id: 84, text: "La zia che ti chiede quando fai figli al funerale del nonno" },
  { id: 85, text: "Il padre che ti spiega come funziona il sesso a 35 anni con il depliant" },
  { id: 86, text: "La sorella che condivide le informazioni intime con tutta la famiglia" },
  { id: 87, text: "Il suocero che ti racconta che lui e tua suocera 'sono ancora attivi'" },
  { id: 88, text: "La mamma che bussa alla porta del bagno ogni 90 secondi" },
  { id: 89, text: "Il fratello che ha letto la tua cronologia del browser e non dice niente" },
  { id: 90, text: "La famiglia riunita che guarda il telefono in silenzio mentre tu spieghi il tuo nuovo partner" },
  // ── Napoletani e Calabresi ────────────────────────────────────────────────
  { id: 91, text: "Il napoletano che ti corteggia con tre vocali e una pizza fritta" },
  { id: 92, text: "Il calabrese che non ti lascia andare a casa tua perché 'prima mangi'" },
  { id: 93, text: "La mamma che entra in camera senza bussare proprio mentre stai" },
  { id: 94, text: "Il sesso così silenzioso da sembrare un esame di stato" },
  { id: 95, text: "Il peto nella jacuzzi dell'hotel a 5 stelle durante il weekend romantico" },
  { id: 96, text: "Il napoletano che urla 'amore mio' così forte che lo sentono tre quartieri" },
  { id: 97, text: "Il ciclo arrivato il giorno del viaggio di nozze — volo di 12 ore" },
  { id: 98, text: "Il sesso sul divano che il giorno dopo spiega al fisioterapista" },
  { id: 99, text: "La ragazza di Napoli che finge di non essere gelosa mentre controlla il telefono" },
  { id: 100, text: "L'erezione spiegata alla suocera come 'problema alla schiena'" },
  { id: 101, text: "Il calabrese convinto che la fedeltà sia una virtù — per lei, non per lui" },
  { id: 102, text: "Il peto durante il massaggio di coppia che rovinaa l'atmosfera a entrambi" },
  { id: 103, text: "La sbronza che porta a mandare foto non richieste all'ex delle 3 di notte" },
  { id: 104, text: "Il napoletano che arriva in ritardo al proprio matrimonio di 45 minuti" },
  { id: 105, text: "Il calabrese con il tatuaggio della Madonna e il carattere del diavolo" },
  // ── Più sesso ─────────────────────────────────────────────────────────────
  { id: 106, text: "Il sesso così rumoroso che i vicini applaudono alla fine" },
  { id: 107, text: "Il sesso in bagno del treno Frecciarossa — con tutta la sua dignità" },
  { id: 108, text: "Il sesso in ufficio dopo le 20 che finisce sul sito del sindacato" },
  { id: 109, text: "Il letto che si rompe a metà — e continuare sul pavimento come eroi" },
  { id: 110, text: "Il sesso così breve che l'altro non se n'è accorto" },
  { id: 111, text: "Il sesso con qualcuno così bravo da renderti inutilizzabile per una settimana" },
  { id: 112, text: "Il sesso dopo 6 mesi di astinenza — 90 secondi di gloria" },
  { id: 113, text: "Il sesso con il partner dei sogni trasformatosi in incubo logistico" },
  { id: 114, text: "Il sesso così atletico da richiedere un riscaldamento preventivo" },
  { id: 115, text: "Il sesso così noioso da finire a guardare il soffitto e pensare alla spesa" },
  { id: 116, text: "Il sesso di vendetta che non risolve niente ma sul momento fa bene" },
  { id: 117, text: "Il sesso in campeggio ascoltato da tutto il campeggio — compresi i bambini" },
  { id: 118, text: "Il sesso durante le Olimpiadi convinti di battere record" },
  { id: 119, text: "Il sesso in piscina che è esattamente difficile quanto sembra" },
  { id: 120, text: "Il sesso programmato sul calendario come riunione — 'appunto fisso giovedì'" },
  // ── Relazioni e tradimenti ────────────────────────────────────────────────
  { id: 121, text: "Il tradimento scoperto grazie al profumo sbagliato sul collo" },
  { id: 122, text: "Il tradimento scoperto perché il telefono ha risposto da solo" },
  { id: 123, text: "Il tradimento scoperto dall'amante che scrive direttamente alla moglie" },
  { id: 124, text: "Il tradimento ammesso durante una lite per tutt'altro motivo" },
  { id: 125, text: "Il tradimento perdonato tre volte con la stessa scusa" },
  { id: 126, text: "Il partner scoperto su Tinder mentre sei ancora insieme" },
  { id: 127, text: "Il partner che tradisce ma nega anche con le prove in mano" },
  { id: 128, text: "Il partner che tradisce e poi fa sentire in colpa te" },
  { id: 129, text: "Il tradimento raccontato a tutti gli amici prima che alla persona tradita" },
  { id: 130, text: "Il tradimento con la migliore amica — il classico" },
  { id: 131, text: "Il tradimento con il migliore amico — il classico di ritorno" },
  { id: 132, text: "La coppia aperta decisa solo da uno dei due" },
  { id: 133, text: "L'ex che torna sempre nei momenti peggiori come una cometa di merda" },
  { id: 134, text: "Il messaggio dell'ex alle 3 di notte: 'sei sveglio/a?'" },
  { id: 135, text: "Il sesso di riconciliazione dopo una lite devastante" },
  // ── Cose corporee ────────────────────────────────────────────────────────
  { id: 136, text: "Il rumore dello stomaco durante il sesso che suona come un basso elettrico" },
  { id: 137, text: "Il sudore così abbondante che serve un asciugamano e un cambio lenzuola" },
  { id: 138, text: "Il morso così forte da lasciare il segno per dieci giorni" },
  { id: 139, text: "Il rutto erotico che spezza ogni atmosfera romantica" },
  { id: 140, text: "Il capello pubico trovato in bocca nel momento meno adatto" },
  { id: 141, text: "Il crampo al polpaccio durante il climax — urlo sbagliato" },
  { id: 142, text: "L'unghia che graffia qualcosa di non previsto" },
  { id: 143, text: "Il tatuaggio in un posto che devi spiegare ogni volta" },
  { id: 144, text: "Il profumo del sudore che si confonde con qualcos'altro" },
  { id: 145, text: "Il livido sul sedere spiegato come 'sono caduto/a dalle scale'" },
  // ── Famiglia parte 2 ──────────────────────────────────────────────────────
  { id: 146, text: "Il figlio che trova il sex toy e lo porta a scuola come show and tell" },
  { id: 147, text: "La mamma che entra in camera e non va più via nonostante i segnali" },
  { id: 148, text: "Il padre che parla di sesso con la stessa competenza di un geologo" },
  { id: 149, text: "I genitori che fanno sesso così rumoroso che i figli adulti escono di casa" },
  { id: 150, text: "Il nonno che racconta le sue conquiste come fossero battaglie napoleoniche" },
  { id: 151, text: "La nonna che dice 'ai miei tempi si faceva di più' con sguardo sognante" },
  { id: 152, text: "Lo zio che porta la fidanzata di 25 anni al Natale di famiglia come bomba a mano" },
  { id: 153, text: "La suocera che commenta il corpo della nuora con naturalezza disarmante" },
  { id: 154, text: "Il suocero che ti dà consigli sul sesso senza che tu li abbia chiesti" },
  { id: 155, text: "Il cognato che ha visto tutto per sbaglio e ha fatto finta di niente — male" },
  // ── Napoletani e Calabresi parte 2 ───────────────────────────────────────
  { id: 156, text: "Il napoletano che gesticola durante il sesso con la stessa energia del discorso" },
  { id: 157, text: "Il calabrese che chiama la mamma ogni giorno a 45 anni — due volte al giorno" },
  { id: 158, text: "Il sesso così energico da rompere il secondo letto in un anno" },
  { id: 159, text: "Il peto della prima mattina di convivenza che sigilla il rapporto per sempre" },
  { id: 160, text: "L'erezione da 70enne che convince di poter fare le cose degli anni '80" },
  { id: 161, text: "Il ciclo così abbondante da richiedere misure di emergenza civile" },
  { id: 162, text: "La sbronza di amaro che porta a spiegare la vita al barista sino alle 4" },
  { id: 163, text: "Il napoletano che fa la pace con un piatto di pasta e aspetta che tu la accetti" },
  { id: 164, text: "Il sesso interrotto dal campanello — sono le suocere con le valigie" },
  { id: 165, text: "Il calabrese che porta i fuochi d'artificio a Ferragosto come contributo romantico" },
  // ── Peti parte 2 ──────────────────────────────────────────────────────────
  { id: 166, text: "Il peto durante il pompino che cambia le regole del gioco" },
  { id: 167, text: "Il peto trattenuto dal primo appuntamento al sesto anno di convivenza" },
  { id: 168, text: "Il peto scoperto come arma di difesa inconsapevole" },
  { id: 169, text: "Il peto al ristorante stellato attribuito al sommelier" },
  { id: 170, text: "Il peto della prima notte insieme — la vera prova del fuoco della relazione" },
  { id: 171, text: "Il peto che sveglia il vicino attraverso tre muri" },
  { id: 172, text: "Il peto sincronizzato di coppia che diventa un momento di complicità" },
  { id: 173, text: "Il peto del cane usato come alibi da entrambi contemporaneamente" },
  { id: 174, text: "Il peto in teatro durante il momento di silenzio più drammatico dell'opera" },
  { id: 175, text: "Il peto di sollievo post-coitale che esprime tutto senza parole" },
  // ── Sbronze parte 2 ──────────────────────────────────────────────────────
  { id: 176, text: "La sbronza che porta a confessare un segreto di 15 anni alla persona sbagliata" },
  { id: 177, text: "La sbronza con l'amaro del nonno che ti risveglia in un altro decennio" },
  { id: 178, text: "La sbronza che convince di poter ballare il twerking a 52 anni" },
  { id: 179, text: "La sbronza di grappa trentina che azzera il senso del pudore" },
  { id: 180, text: "La sbronza di Carnevale che dura fino alla domenica delle Palme" },
  { id: 181, text: "La sbronza di vino siciliano che inizia a pranzo e finisce a pranzo il giorno dopo" },
  { id: 182, text: "La sbronza durante la quale hai deciso di smettere di bere — ancora sbronzo/a" },
  { id: 183, text: "La sbronza che ti fa credere di essere fluente in spagnolo davanti agli spagnoli" },
  { id: 184, text: "La sbronza di San Silvestro che porta a fare cose che si vedranno su YouTube" },
  { id: 185, text: "La sbronza che ti fa postare una foto con il tuo ex come 'nostalgia'" },
  // ── Sesso strano ─────────────────────────────────────────────────────────
  { id: 186, text: "Il fetish scoperto per caso e mai più dimenticato" },
  { id: 187, text: "Il gioco di ruolo che finisce male perché nessuno si ricorda chi fa cosa" },
  { id: 188, text: "Le manette comprate online arrivate in un pacco da Amazon col logo enorme" },
  { id: 189, text: "Il set BDSM assemblato con la corda del bucato e una cravatta" },
  { id: 190, text: "Il lattice che produce un'allergia scoperta nel momento peggiore" },
  { id: 191, text: "Il tentativo di sesso tantrico finito in una crisi di ilarità" },
  { id: 192, text: "Il video osé girato per uso personale e trovato dalla mamma per sbaglio" },
  { id: 193, text: "L'app per adulti aperta per sbaglio durante la presentazione di lavoro" },
  { id: 194, text: "Il sextoy ordinato di fretta sbagliando le dimensioni" },
  { id: 195, text: "Il lubrificante usato al posto della crema idratante per sbaglio" },
  // ── Erezioni parte 2 ─────────────────────────────────────────────────────
  { id: 196, text: "L'erezione causata dall'annuncio dei saldi al supermercato" },
  { id: 197, text: "L'erezione durante il discorso del prete alla cresima del nipote" },
  { id: 198, text: "L'erezione a bordo piscina con il costume da bagno bianco" },
  { id: 199, text: "L'erezione improvvisa durante il massaggio dalla fisioterapista" },
  { id: 200, text: "L'erezione da Viagra il mattino del matrimonio — tre ore prima della cerimonia" },
  { id: 201, text: "L'erezione in macchina al casello — e il pagamento contactless non funziona" },
  { id: 202, text: "L'erezione all'esame del professore temuto — spiegazioni impossibili" },
  { id: 203, text: "L'erezione da sogno erotico al risveglio con ospiti in casa" },
  { id: 204, text: "L'erezione mentre leggi i termini e condizioni su siti per adulti" },
  { id: 205, text: "L'erezione che dura il giusto per trovare nessuno disponibile" },
  // ── Ciclo parte 2 ────────────────────────────────────────────────────────
  { id: 206, text: "Il ciclo arrivato in piscina trasformando l'acqua in una scena del Padrino" },
  { id: 207, text: "Il ciclo che arriva proprio quando stai per fare sesso dopo mesi" },
  { id: 208, text: "Il ciclo abbondante che richiede l'assorbente industriale e i pantaloni scuri" },
  { id: 209, text: "Il ciclo che trasforma una persona ragionevole in un boss finale di videogioco" },
  { id: 210, text: "Il ciclo con dolori tali da giustificare morfina e un medico legale" },
  { id: 211, text: "Il ciclo in vacanza che rovina il piano del costume intero senza spalline" },
  { id: 212, text: "Il ciclo della ragazza che il fidanzato nordico non capisce e mai capirà" },
  { id: 213, text: "Il ciclo che torna dopo tre mesi di 'ritardo fisiologico' portando panico" },
  { id: 214, text: "Il ciclo che arriva un'ora prima di un appuntamento importante da un anno" },
  { id: 215, text: "Il ciclo usato strategicamente per evitare la cena con i suoceri" },
  // ── Famiglia parte 3 ──────────────────────────────────────────────────────
  { id: 216, text: "Il padre che fa commenti sul peso ogni volta che ti vede" },
  { id: 217, text: "La mamma che chiede 'quando ti sposi' a ogni funerale e battesimo" },
  { id: 218, text: "Il nonno che mette la mano sul culo e dice 'un tempo si poteva'" },
  { id: 219, text: "La zia che ti porta il ragazzo/a di cugino come potenziale partner" },
  { id: 220, text: "Il fratello maggiore che ha combinato molto peggio di te e giudica" },
  { id: 221, text: "La sorella che racconta tutto alla mamma il giorno stesso" },
  { id: 222, text: "Lo zio alcolizzato che è comunque il più divertente di tutti" },
  { id: 223, text: "La suocera che arriva senza avvisare mentre fate sesso" },
  { id: 224, text: "Il padre del partner che ti guarda come se sapesse già tutto di te" },
  { id: 225, text: "Il cugino trovato su Grindr con nome e foto diverse" },
  // ── Napoletani e Calabresi parte 3 ───────────────────────────────────────
  { id: 226, text: "Il napoletano che piange più a un funerale finto di un film che al vero" },
  { id: 227, text: "Il sesso così breve da sembrare un errore di sistema" },
  { id: 228, text: "Il calabrese che spiega l'onore mentre fa l'esatto contrario" },
  { id: 229, text: "Il peto in ascensore con il nuovo partner al terzo appuntamento" },
  { id: 230, text: "Il ciclo che arriva all'esame di laurea con pantaloni bianchi scelti quel mattino" },
  { id: 231, text: "La sbronza che porta a ballare il tango da soli in mezzo alla piazza" },
  { id: 232, text: "Il napoletano che considera 'tardi' qualsiasi ora prima delle 23" },
  { id: 233, text: "L'erezione durante il colloquio di lavoro col capo più temuto dell'azienda" },
  { id: 234, text: "Il sesso in tenda al campeggio amplificato perfettamente dalla notte silenziosa" },
  { id: 235, text: "Il calabrese che ha la pistola per le feste e il sugo per le guerre" },
  // ── Peti parte 3 ─────────────────────────────────────────────────────────
  { id: 236, text: "Il peto così lungo da meritare una standing ovation" },
  { id: 237, text: "Il peto notturno che spaventa il cane e sveglia la casa" },
  { id: 238, text: "Il peto in chiesa durante la benedizione pasquale" },
  { id: 239, text: "Il peto silenzioso ma tossico che fa evacuare la stanza" },
  { id: 240, text: "Il peto che accompagna ogni discesa dalle scale con precisione militare" },
  { id: 241, text: "Il peto durante l'ecografia che imbarazza il medico e diverte l'ecografista" },
  { id: 242, text: "Il peto di nervi che arriva sempre nel momento più solenne" },
  { id: 243, text: "Il peto della prima notte di convivenza che segna la fine del mistero" },
  { id: 244, text: "Il peto in macchina con i finestrini chiusi — rapporti di coppia a rischio" },
  { id: 245, text: "Il peto liberatorio post-cena della nonna attribuito al marito da 50 anni" },
  // ── Situazioni sessuali imbarazzanti ─────────────────────────────────────
  { id: 246, text: "Il figlio che trova la cronologia di Pornhub del padre — poi li confrontano" },
  { id: 247, text: "Il sesso così scadente da controllare il telefono a metà" },
  { id: 248, text: "Il sesso con qualcuno che geme come un personaggio di un film di Mario Bava" },
  { id: 249, text: "Il sesso con qualcuno che parla troppo — e dice le cose sbagliate" },
  { id: 250, text: "Il sesso in cui qualcuno morde un orecchio e l'altro urla per il dolore vero" },
  { id: 251, text: "Il sesso scoperto dalla mappa di geolocalizzazione condivisa per caso" },
  { id: 252, text: "Il sesso di coppia trasformato in monologo da uno dei due" },
  { id: 253, text: "Il sesso interrotto da una telefonata del lavoro — presa per timore del licenziamento" },
  { id: 254, text: "Il sesso in piedi che rivela differenze di altezza non contemplate" },
  { id: 255, text: "Il sesso così energico da togliere il quadro dal muro" },
  // ── Sbronze parte 3 ──────────────────────────────────────────────────────
  { id: 256, text: "La sbronza di Pasqua con la colomba e quattro bottiglie di Sagrantino" },
  { id: 257, text: "La sbronza che porta a dichiarare guerra ai vicini sul gruppo WhatsApp del condominio" },
  { id: 258, text: "La sbronza di gin tonic che trasforma un timido in un oratore da piazza" },
  { id: 259, text: "La sbronza che porta a ordinare 200 euro di sushi alle 3 di notte" },
  { id: 260, text: "La sbronza che porta a tatuarsi 'carpe diem' in corsivo sul polso" },
  { id: 261, text: "La sbronza che fa sembrare una buona idea suonare il campanello dell'ex" },
  { id: 262, text: "La sbronza di birra artigianale che finisce con sei persone nel bagno" },
  { id: 263, text: "La sbronza di champagne che si rivela essere Cava — due giorni di vergogna" },
  { id: 264, text: "La sbronza che porta a diventare migliori amici con qualcuno che non si rivede mai" },
  { id: 265, text: "La sbronza che dura tre giorni nonostante le promesse di 'solo un bicchiere'" },
  // ── Relazioni dis-funzionali ─────────────────────────────────────────────
  { id: 266, text: "Il partner che giudica i tuoi peti ma ne fa di peggio in segreto" },
  { id: 267, text: "Il partner che trasforma ogni discussione in un'interrogazione" },
  { id: 268, text: "Il partner che dorme sul lato sbagliato e non lo ammetterà mai" },
  { id: 269, text: "Il partner che apre il pacchetto di patatine alle 2 di notte con precisione chirurgica" },
  { id: 270, text: "Il partner che usa il 'non ho sentito' come scudo universale da 7 anni" },
  { id: 271, text: "Il partner che chiede 'a cosa stai pensando' durante il sesso" },
  { id: 272, text: "Il partner che mangia tutte le patatine e mette il sacchetto vuoto nella dispensa" },
  { id: 273, text: "Il partner che vuole parlare di sentimenti alle 11:47 di domenica sera" },
  { id: 274, text: "Il partner che usa la testata del letto come lavagna — segni dappertutto" },
  { id: 275, text: "Il partner che si soffia il naso durante il sesso — tipo tre volte" },
  // ── Napoletani e Calabresi parte 4 ───────────────────────────────────────
  { id: 276, text: "Il sesso con qualcuno che si addormenta a metà e poi nega" },
  { id: 277, text: "Il peto durante il discorso degli sposi al proprio matrimonio" },
  { id: 278, text: "Il napoletano che fa la pace con un piatto di pasta e aspetta che tu la accetti" },
  { id: 279, text: "Il calabrese con il tatuaggio della Madonna e il carattere del diavolo" },
  { id: 280, text: "Il ciclo che costringe a cancellare un appuntamento già rimandato 4 volte" },
  { id: 281, text: "La sbronza che porta a piangere vedendo uno spot del Mulino Bianco" },
  { id: 282, text: "L'erezione al funerale — non si capisce perché e non si può spiegare" },
  { id: 283, text: "Il sesso registrato per sbaglio sull'app note del telefono" },
  { id: 284, text: "Il napoletano che guida col clacson come strumento musicale principale" },
  { id: 285, text: "Il peto del neonato durante il battesimo che fa ridere solo il padrino" },
  // ── Corpo e imbarazzo ────────────────────────────────────────────────────
  { id: 286, text: "Il segno del ciclo sul jeans beige in metropolitana con 200 persone intorno" },
  { id: 287, text: "Il cesso condiviso con il nuovo partner per la prima volta" },
  { id: 288, text: "La prima doccia insieme che rivela molto più del previsto" },
  { id: 289, text: "Il russare così forte da far svegliare l'altra metà del palazzo" },
  { id: 290, text: "Il moccio allergico durante un bacio romantico all'aperto" },
  { id: 291, text: "Il vomito da troppa ansia del primo appuntamento — al ristorante" },
  { id: 292, text: "La diarrea da nervosismo prima di conoscere i genitori di lei/lui" },
  { id: 293, text: "Il sudore freddo durante il sesso che inspiegabilmente peggiora tutto" },
  { id: 294, text: "Il capello pubico nel dente durante una cena con candele" },
  { id: 295, text: "La vescica che decide di cooperare durante il sesso senza preavviso" },
  // ── Sbronze parte 4 ──────────────────────────────────────────────────────
  { id: 296, text: "La sbronza che rivela chi sei davvero — e non è un complimento" },
  { id: 297, text: "La sbronza che porta a mandare il messaggio sbagliato alla persona sbagliata" },
  { id: 298, text: "La sbronza di limoncello che finisce con la testa nel cespuglio" },
  { id: 299, text: "La sbronza di birra tedesca che ti convince di capire il tedesco" },
  { id: 300, text: "La sbronza che porta a chiamare la ex, poi il capo, poi la mamma — in ordine" },
  { id: 301, text: "La sbronza che finisce con dormire sul pavimento del bagno come scelta consapevole" },
  { id: 302, text: "La sbronza di Ferragosto con i cognati che dura tre giorni e non finisce mai" },
  { id: 303, text: "La sbronza che porta a credere di saper fare il DJ — con il telefono connesso in Bluetooth" },
  { id: 304, text: "La sbronza che ti fa abbracciare il cane del vicino come se fosse il tuo" },
  { id: 305, text: "La sbronza che porta a ordinare 15 arancini alle 4 di mattina a Palermo" },
  // ── Sesso vario ───────────────────────────────────────────────────────────
  { id: 306, text: "Il sesso con qualcuno incontrato 4 ore prima a un matrimonio" },
  { id: 307, text: "Il sesso di addio durato tre mesi" },
  { id: 308, text: "Il sesso così rumoroso che il vicinato fa il tifo" },
  { id: 309, text: "Il sesso durante la pausa pubblicitaria di una serie TV" },
  { id: 310, text: "Il sesso via videochiamata che va in background per sbaglio" },
  { id: 311, text: "Il sesso nel bagno del locale — con la fila fuori" },
  { id: 312, text: "Il sesso che inizia romanticamente e finisce per colpa di un crampo" },
  { id: 313, text: "Il sesso con qualcuno che dice il proprio nome in terza persona durante" },
  { id: 314, text: "Il sesso che convince entrambi di dover fare yoga" },
  { id: 315, text: "Il sesso in macchina che fa squillare l'antifurto due volte" },
  // ── Ciclo parte 3 ────────────────────────────────────────────────────────
  { id: 316, text: "Il ciclo della collega che sincronizza quello di tutto l'ufficio femminile" },
  { id: 317, text: "Il ciclo abbondante che trasforma la doccia in una scena crime" },
  { id: 318, text: "Il ciclo che arriva il giorno prima delle vacanze al mare ogni anno" },
  { id: 319, text: "Il ciclo con coaguli che il partner scopre e non sa come reagire" },
  { id: 320, text: "Il ciclo durante l'esame orale che aggiunge un livello extra di terrore" },
  { id: 321, text: "Il ciclo negato al partner che 'non capisce queste cose'" },
  { id: 322, text: "Il ciclo alle terme — esperienza da non ripetere e da non descrivere" },
  { id: 323, text: "Il ciclo così doloroso da giustificare l'assenza al lavoro per tre giorni" },
  { id: 324, text: "Il ciclo arrivato il giorno del primo sesso — karma immediato" },
  { id: 325, text: "Il ciclo irregular che il ginecologo chiama 'carattere'" },
  // ── Famiglia parte 4 ─────────────────────────────────────────────────────
  { id: 326, text: "Il padre che compra Pornhub Premium e lo trova nella carta di credito condivisa" },
  { id: 327, text: "La mamma che ti manda articoli su 'come trovare l'uomo/donna giusta'" },
  { id: 328, text: "Il nonno che spiega come 'ai tempi suoi' le donne erano diverse — e rideva" },
  { id: 329, text: "La sorella che scopre il tuo profilo su un'app di incontri e ti manda il match" },
  { id: 330, text: "Lo zio che porta il nipote al casino il giorno del 18esimo come tradizione" },
  { id: 331, text: "Il cugino che ha fatto la stessa cosa di te ma con più successo e ne parla ancora" },
  { id: 332, text: "La nonna che usa WhatsApp e manda vocali di 11 minuti sulle cose del corpo" },
  { id: 333, text: "Il padre che trova i messaggi senza capire come li ha trovati" },
  { id: 334, text: "La madre che entra durante la masturbazione e finge di non aver visto — entrambi" },
  { id: 335, text: "Il fratello che ha letto il tuo diario segreto e ti fa capire che sa tutto" },
  // ── Napoletani e Calabresi parte 5 ───────────────────────────────────────
  { id: 336, text: "Il napoletano che arriva in ritardo al proprio matrimonio" },
  { id: 337, text: "Il sesso con la musica sbagliata — 'Azzurro' di Celentano in loop" },
  { id: 338, text: "Il calabrese che chiama la mamma ogni giorno a 45 anni — due volte" },
  { id: 339, text: "Il ciclo arrivato durante un'ora di yoga hot in studio affollato" },
  { id: 340, text: "La sbronza che porta a credere di saper fare la ruota in discoteca a 48 anni" },
  { id: 341, text: "L'erezione mattutina che blocca l'accesso al bagno per 20 minuti" },
  { id: 342, text: "Il peto che suona esattamente come una nota riconoscibile di 'Volare'" },
  { id: 343, text: "Il napoletano che non riesce a stare in silenzio nemmeno in chiesa" },
  { id: 344, text: "Il sesso così acrobatico da richiedere una visita fisioterapica il lunedì" },
  { id: 345, text: "Il calabrese che considera i fuochi d'artificio per Ferragosto un diritto inviolabile" },
  // ── Peti parte 4 ─────────────────────────────────────────────────────────
  { id: 346, text: "Il peto durante lo yoga con la testa delle altre partecipanti vicina" },
  { id: 347, text: "Il peto della suocera attribuito al cane da tutti per educazione" },
  { id: 348, text: "Il peto così potente da far saltare le candele romantiche sul tavolo" },
  { id: 349, text: "Il peto al pronto soccorso mentre si aspetta con dignità" },
  { id: 350, text: "Il peto dell'anziano professore durante il discorso alla laurea" },
  { id: 351, text: "Il peto in aereo con tre ore di volo davanti e nessuno che muove un muscolo" },
  { id: 352, text: "Il peto del presidente del consiglio di condominio durante la riunione" },
  { id: 353, text: "Il peto di paura al colloquio di lavoro che viene comunque preso" },
  { id: 354, text: "Il peto che suona come una nota musicale riconoscibile" },
  { id: 355, text: "Il peto liberatorio dopo tre ore di cena di lavoro costretta" },
  // ── Sesso con complicazioni ────────────────────────────────────────────────
  { id: 356, text: "Il sesso durante la quale squilla il citofono — sono i suoceri" },
  { id: 357, text: "Il sesso interrotto dalla notifica della pizza in consegna — priorità difficili" },
  { id: 358, text: "Il sesso in cui qualcuno chiede 'questo ti piace?' ogni 45 secondi" },
  { id: 359, text: "Il sesso in cui la playlist romantica mette 'Azzurro' di Celentano" },
  { id: 360, text: "Il sesso durante il quale il telefono legge ad alta voce un messaggio dell'ex" },
  { id: 361, text: "Il sesso durante la quale il cane sale sul letto e si siede a guardare" },
  { id: 362, text: "Il sesso con qualcuno che ha troppa energia rispetto alle tue aspettative" },
  { id: 363, text: "Il sesso in spiaggia con la sabbia che trasforma tutto in un'esperienza geologica" },
  { id: 364, text: "Il sesso di coppia diventato quasi professionale dopo 15 anni — noioso ma preciso" },
  { id: 365, text: "Il sesso sul divano dei genitori scoperto dopo da entrambe le famiglie" },
  // ── Erezioni parte 3 ─────────────────────────────────────────────────────
  { id: 366, text: "L'erezione causata da una voce al telefono — professionale e contestuale" },
  { id: 367, text: "L'erezione durante il massaggio shiatsu del martedì pomeriggio" },
  { id: 368, text: "L'erezione al funerale — non si capisce perché e non si può spiegare" },
  { id: 369, text: "L'erezione che compare durante la discussione di divorzio col notaio" },
  { id: 370, text: "L'erezione notturna automatica che sveglia il partner — non è un invito" },
  { id: 371, text: "L'erezione nel confessionale — il prete ha visto di peggio, si presume" },
  { id: 372, text: "L'erezione da 70enne che convince di poter fare cose degli anni '80" },
  { id: 373, text: "L'erezione al supermercato causata dal reparto verdure — non si sa perché" },
  { id: 374, text: "L'erezione durante il dentista che aggiunge un livello al disagio" },
  { id: 375, text: "L'erezione non desiderata all'esame di guida accanto all'esaminatrice" },
  // ── Sbronze parte 5 ──────────────────────────────────────────────────────
  { id: 376, text: "La sbronza con lo zio terribile che si rivela la persona più divertente della famiglia" },
  { id: 377, text: "La sbronza di rum che porta a ballare la salsa davanti alla fermata del tram" },
  { id: 378, text: "La sbronza che porta a mandare 37 messaggi vocali all'ex tra le 2 e le 4" },
  { id: 379, text: "La sbronza che finisce con una multa, un matrimonio e un tatuaggio nello stesso giorno" },
  { id: 380, text: "La sbronza di vino rosso che tinge i denti e dimentichi per l'intera serata" },
  { id: 381, text: "La sbronza che porta a fare una promessa impossibile a qualcuno che la ricorderà" },
  { id: 382, text: "La sbronza di whisky che trasforma un silenzioso in un filosofo da bar" },
  { id: 383, text: "La sbronza che finisce con la testa nel cespuglio del vicino" },
  { id: 384, text: "La sbronza di Natale che rivela la vera opinione di tutti su tutto" },
  { id: 385, text: "La sbronza di prosecco a 40 anni che ti ricorda perché smettesti a 30" },
  // ── Relazioni italiane ────────────────────────────────────────────────────
  { id: 386, text: "Il fidanzato che porta il sugo della mamma al primo appuntamento come portata principale" },
  { id: 387, text: "Il partner che piange ogni volta che finisce la pasta nel piatto" },
  { id: 388, text: "Il partner che considera fare il bucato insieme un atto di intimità" },
  { id: 389, text: "Il partner che mangia l'ultima mozzarella e nega con gli occhi del cane basset" },
  { id: 390, text: "Il partner che usa il bidet e lo considera superiore al sesso" },
  { id: 391, text: "Il partner che fa pipì con la porta aperta dal sesto mese di relazione" },
  { id: 392, text: "Il partner che taglia la pizza con le forbici e pensa sia normale" },
  { id: 393, text: "Il partner che mette il ketchup sulla pasta e bisogna lasciarlo" },
  { id: 394, text: "Il partner che dice 'non ho fame' e poi mangia la metà del tuo piatto" },
  { id: 395, text: "Il partner che fa i capricci al ristorante perché 'non cucina come la mamma'" },
  // ── Ciclo parte 4 ────────────────────────────────────────────────────────
  { id: 396, text: "Il ciclo in vacanza con il bianco che serviva per la cena elegante" },
  { id: 397, text: "Il ciclo che convince il fidanzato di dover imparare a comprare gli assorbenti" },
  { id: 398, text: "Il ciclo che arriva durante la luna di miele come ospite non invitato" },
  { id: 399, text: "Il ciclo irregolare che il medico chiama 'personalità' della paziente" },
  { id: 400, text: "Il ciclo che viene usato per rimandare cose importanti già da 6 mesi" },
  // ── Peti finali ───────────────────────────────────────────────────────────
  { id: 401, text: "Il peto del bambino durante il battesimo — eppure è il momento più sincero" },
  { id: 402, text: "Il peto in sauna che fa uscire tutti con dignità variabile" },
  { id: 403, text: "Il peto di sollievo post-operatorio che il medico chiama 'ottimo segnale'" },
  { id: 404, text: "Il peto del ragazzo di Napoli che poi gesticola come a dire 'non sono stato io'" },
  { id: 405, text: "Il peto in macchina che hai aspettato cinque km per fare ma hai sbagliato il momento" },
  { id: 406, text: "Il peto matutino prima del caffè — la vera colazione italiana" },
  { id: 407, text: "Il peto che accompagna ogni tentativo di alzarsi dal divano oltre i 40 anni" },
  { id: 408, text: "Il peto prodotto da un piatto di fagioli alle 23 prima del sesso" },
  { id: 409, text: "Il peto in biblioteca universitaria che tutti sentono ma nessuno guarda" },
  { id: 410, text: "Il peto di fine anno che aspettavi da 365 giorni — liberatorio" },
  // ── Mix finale ────────────────────────────────────────────────────────────
  { id: 411, text: "Il sesso con qualcuno che piange alla fine senza motivo dichiarato" },
  { id: 412, text: "L'erezione al matrimonio altrui che nessuno dovrebbe notare" },
  { id: 413, text: "Il ciclo arrivato durante la visita al museo — in costume bianco" },
  { id: 414, text: "La sbronza che porta a confessare tutto alla mamma in videochiamata" },
  { id: 415, text: "Il peto durante la cerimonia di laurea con toga e tocco" },
  { id: 416, text: "Il figlio che trova il diario segreto e lo legge a voce alta al cena" },
  { id: 417, text: "Il napoletano che urla 'ti voglio bene' così forte che sentono i vicini di Caserta" },
  { id: 418, text: "Il partner che fa il peto e poi annusa l'aria con soddisfazione" },
  { id: 419, text: "Il ciclo della fidanzata scoperto dal fidanzato leggendo WhatsApp per sbaglio" },
  { id: 420, text: "La sbronza che porta a giocare a poker alle 4 di notte con i suoceri" },
  { id: 421, text: "Il sesso in pullman durante la gita scolastica dei 40enni" },
  { id: 422, text: "L'erezione durante il massaggio dei piedi al centro benessere" },
  { id: 423, text: "Il peto mentre fai la piega dal parrucchiere — cappetta compresa" },
  { id: 424, text: "La mamma che trova la chat piccante e chiede spiegazioni a cena" },
  { id: 425, text: "Il calabrese che porta lupini, birra e i fratelli come scorta al primo appuntamento" },
  { id: 426, text: "Il ciclo in piscina con la cupola olimpionica — scandalo nazionale" },
  { id: 427, text: "La sbronza di vino novello che porta a fare cose che non si ricordano" },
  { id: 428, text: "Il sesso così breve che il partner crede ci sia stato un black out" },
  { id: 429, text: "Il peto che fa svegliare il figlio che dormiva finalmente" },
  { id: 430, text: "L'erezione mentre la suocera racconta come era bello tuo marito da giovane" },
  { id: 431, text: "Il napoletano che considera le 20:00 ora di aperitivo — la cena è alle 22:30" },
  { id: 432, text: "Il ciclo che arriva il giorno della visita ginecologica — ovviamente" },
  { id: 433, text: "La sbronza di digestivo che porta a risolvere tutti i problemi dell'umanità" },
  { id: 434, text: "Il sesso con qualcuno così bello da sembrare un errore di casting" },
  { id: 435, text: "Il peto durante la meditazione guidata che interrompe il silenzio cosmico" },
  { id: 436, text: "La famiglia di Napoli che arriva a sorpresa — con 14 persone, 40 kg di cibo e nessun preavviso" },
  { id: 437, text: "L'erezione mattutina invitata al bagno — lunga attesa" },
  { id: 438, text: "Il ciclo con dolori spiegati come 'normale fisiologia' da un medico maschio" },
  { id: 439, text: "La sbronza che porta a iscriversi a un corso di cucina napoletana a mezzanotte" },
  { id: 440, text: "Il peto del suocero durante il gioco di carte di Natale — game changer" },
  { id: 441, text: "Il sesso di coppia così raro da essere commemorato come un evento" },
  { id: 442, text: "Il napoletano che considera la puntualità una forma di aggressione passiva" },
  { id: 443, text: "Il ciclo arrivato in aereo con assorbente scaduto nel beauty case" },
  { id: 444, text: "La sbronza che porta a piangere per un cane visto per strada dieci anni fa" },
  { id: 445, text: "L'erezione durante la cerimonia di premiazione del concorso letterario" },
  { id: 446, text: "Il peto che si sente dal piano di sotto come basso continuo" },
  { id: 447, text: "La famiglia di Calabria che commenta il tuo corpo sin dal primo saluto con naturalezza disarmante" },
  { id: 448, text: "Il sesso così rumoroso da ricevere applausi dal piano sopra" },
  { id: 449, text: "Il ciclo della ragazza di Napoli spiegato al fidanzato milanese che non capisce e non capirà mai" },
  { id: 450, text: "La sbronza di San Giovanni che si concluse con un giuramento" },
  // ── Ultime 50 ─────────────────────────────────────────────────────────────
  { id: 451, text: "Il sesso dopo 12 ore di viaggio in treno — odore incluso" },
  { id: 452, text: "Il peto così tempestivo da sembrare una firma su un documento" },
  { id: 453, text: "Il ciclo dimenticato finché il lenzuolo non lo ricorda" },
  { id: 454, text: "La sbronza di rosso con i suoceri che rivela troppo su troppo" },
  { id: 455, text: "L'erezione in vasca da bagno che crea un ostacolo galleggiante" },
  { id: 456, text: "Il napoletano che porta tre pizze al pronto soccorso come offerta di pace" },
  { id: 457, text: "Il sesso che dura meno della pubblicità prima di un video su YouTube" },
  { id: 458, text: "Il peto in spa che viene classificato come 'bolla termale'" },
  { id: 459, text: "La mamma che sistema il letto degli ospiti e trova cose che nessuno vuole trovare" },
  { id: 460, text: "Il ciclo arrivato 5 minuti prima del sesso più atteso dell'anno" },
  { id: 461, text: "La sbronza di limoncello in Costiera che porta a saltare dal pontile" },
  { id: 462, text: "Il sesso con qualcuno che fa commenti tecnici come un allenatore durante" },
  { id: 463, text: "Il napoletano a Milano che piange per il mare ogni volta che piove e ogni volta che non piove" },
  { id: 464, text: "L'erezione durante il discorso del nonno a tavola — nessuno ha detto niente" },
  { id: 465, text: "Il peto del cane usato come copertura con successo variabile" },
  { id: 466, text: "Il ciclo abbondante durante la prova abito da sposa — tragedia bianca" },
  { id: 467, text: "La sbronza che porta a cambiare nome su tutti i profili social alle 3 di notte" },
  { id: 468, text: "Il sesso in campagna con i grilli come colonna sonora e la mucca come testimone" },
  { id: 469, text: "La famiglia di Napoli che cena alle 22:30 e il genero nordico crolla alle 21:15" },
  { id: 470, text: "L'erezione incontrollabile alla prima visita dal nuovo medico" },
  { id: 471, text: "Il peto durante la visita in museo — eco perfetto nella sala degli Uffizi" },
  { id: 472, text: "La sbronza che porta a cantare 'O sole mio' in treno — senza essere napoletano" },
  { id: 473, text: "Il ciclo con sindrome premestruale che trasforma un normale mercoledì in Guerra e Pace" },
  { id: 474, text: "Il sesso così nervoso da rompere accidentalmente un quadro della suocera" },
  { id: 475, text: "Il napoletano che porta la mamma all'honeymoon 'per dare una mano'" },
  { id: 476, text: "Il peto trattenuto durante un'intera cerimonia nuziale — uscita trionfale" },
  { id: 477, text: "L'erezione che arriva solo quando non serve mai quando serve" },
  { id: 478, text: "La sbronza di Natale che porta a rivelare i regali già prima del 25" },
  { id: 479, text: "Il ciclo che la mamma diagnostica in anticipo guardandoti in faccia" },
  { id: 480, text: "Il sesso con qualcuno così bello da star male il giorno dopo per le aspettative" },
  { id: 481, text: "Il napoletano che spiega la differenza tra il sugo di sua madre e il tuo con disegni e lacrime" },
  { id: 482, text: "Il peto della nonna che interrompe il silenzio durante la preghiera del rosario" },
  { id: 483, text: "L'erezione vista dalla professoressa di ginnastica — lei ha fatto finta di niente, lui no" },
  { id: 484, text: "La sbronza che porta a sposarsi a Las Vegas con qualcuno conosciuto quel giorno" },
  { id: 485, text: "Il ciclo che arriva durante la riunione di lavoro più importante dell'anno" },
  { id: 486, text: "Il sesso in stazione ferroviaria con il treno delle 23:47 che parte puntuale" },
  { id: 487, text: "Il peto di rabbia che esce durante una discussione di coppia come argomento finale" },
  { id: 488, text: "La famiglia calabrese che considera il pranzo domenicale un sacramento da 6 ore" },
  { id: 489, text: "L'erezione mattutina spiegata come 'ho freddo' — non convince nessuno" },
  { id: 490, text: "La sbronza che finisce con il capo che ti chiama e rispondi ancora ubriaco" },
  { id: 491, text: "Il ciclo di coppia sincronizzato per sbaglio — nessuno capisce come" },
  { id: 492, text: "Il sesso con il gatto che fissa dall'angolo con giudizio visibile" },
  { id: 493, text: "Il peto durante la seduta con il/la terapeuta — il silenzio dura 3 minuti" },
  { id: 494, text: "Il calabrese che a 50 anni chiama ancora la mamma 'mammina' senza vergogna — due volte al giorno" },
  { id: 495, text: "L'erezione che porta il pensiero alle cose più banali — lista della spesa" },
  { id: 496, text: "La sbronza che porta a costruire un'alleanza con il cane del vicino" },
  { id: 497, text: "Il ciclo che il fidanzato nordico segna sul foglio excel mensile" },
  { id: 498, text: "Il sesso sul balcone convinti che nessuno guardi — e il vicino dirimpettaio si gode lo spettacolo" },
  { id: 499, text: "Il peto in chiesa al momento dell'alzate il calice — si alzano anche le sopracciglia" },
  { id: 500, text: "Il sesso così memorabile da rovinare tutti quelli successivi come metro di confronto" },
]

export function shuffleArray<T>(array: T[]): T[] {
  const arr = [...array]
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr
}

export function getAnswerById(id: number): AnswerCard | undefined {
  return ANSWERS.find(a => a.id === id)
}

export function getQuestionById(id: number): QuestionCard | undefined {
  return QUESTIONS.find(q => q.id === id)
}
