import type { QuestionCard, AnswerCard } from '@/types/game'

export const QUESTIONS: QuestionCard[] = [
  { id: 1, text: "La cosa che fai subito dopo il sesso ma non ammetteresti mai è ___" },
  { id: 2, text: "Il modo peggiore per scoprire che il tuo partner ti tradisce è ___" },
  { id: 3, text: "Cosa non dovresti mai mandare per messaggio all'ex? ___" },
  { id: 4, text: "Il segreto per mantenere vivo il desiderio dopo 10 anni insieme è ___" },
  { id: 5, text: "La cosa più italiana da fare durante il sesso è ___" },
  { id: 6, text: "Il momento peggiore per scoprire di non avere i preservativi è ___" },
  { id: 7, text: "Cosa cambia nella vita sessuale dopo i 40 anni? ___" },
  { id: 8, text: "Il regalo più inappropriato da fare alla suocera è ___" },
  { id: 9, text: "Come si sopravvive a Natale sapendo che i tuoi genitori fanno ancora sesso? ___" },
  { id: 10, text: "La cosa più imbarazzante che può capitare durante il sesso è ___" },
  { id: 11, text: "Il problema principale degli italiani a letto è ___" },
  { id: 12, text: "Cosa fa un italiano quando il partner non ha voglia? ___" },
  { id: 13, text: "Il modo migliore per portarsi a casa qualcuno al bar è ___" },
  { id: 14, text: "Il rimedio della nonna per il calo del desiderio è ___" },
  { id: 15, text: "La cosa che un italiano fa meglio di tutti in camera da letto è ___" },
  { id: 16, text: "Come si riconosce qualcuno che non fa sesso da troppo tempo? ___" },
  { id: 17, text: "Il momento peggiore per chiamare la mamma è ___" },
  { id: 18, text: "Come ci si prepara per una notte che non si dimentica? ___" },
  { id: 19, text: "Cosa non può mai mancare nel cassetto del comodino? ___" },
  { id: 20, text: "Il lavoro più utile dopo una relazione finita male è ___" },
  { id: 21, text: "Come si convincono i suoceri che sei la persona giusta senza mentire troppo? ___" },
  { id: 22, text: "La cosa più difficile da spiegare al partner dopo una notte fuori è ___" },
  { id: 23, text: "Perché le mamme italiane sanno sempre quando hai fatto sesso? ___" },
  { id: 24, text: "Il momento in cui capisci che la storia è finita davvero è ___" },
  { id: 25, text: "Cosa fa un uomo italiano di 60 anni quando scopre Tinder? ___" },
  { id: 26, text: "Il modo peggiore per iniziare un'avventura di una notte è ___" },
  { id: 27, text: "La scusa migliore per tornare a casa alle 7 di mattina è ___" },
  { id: 28, text: "Cosa succede quando il partner scopre la tua cronologia del browser? ___" },
  { id: 29, text: "Come si trova un appuntamento decente a Roma? ___" },
  { id: 30, text: "La cosa più assurda che fa un italiano per conquistare qualcuno all'estero è ___" },
  { id: 31, text: "Il modo migliore per evitare il sesso nel periodo di crisi di coppia è ___" },
  { id: 32, text: "Perché gli italiani credono di essere i migliori amanti del mondo? ___" },
  { id: 33, text: "La peggiore giustificazione per non avere voglia è ___" },
  { id: 34, text: "Cosa succede se dici a un italiano che il suo modo di fare l'amore è noioso? ___" },
  { id: 35, text: "Il momento più eccitante della settimana in una coppia di lunga data è ___" },
  { id: 36, text: "Come si capisce che qualcuno vuole portarti a letto senza dirlo? ___" },
  { id: 37, text: "Il peggior complimento che puoi fare a qualcuno a letto è ___" },
  { id: 38, text: "Cosa fa un politico italiano quando viene beccato con l'amante? ___" },
  { id: 39, text: "Il rimedio universale per rimettere pepe in una relazione è ___" },
  { id: 40, text: "La cosa più strana trovata nel comodino di un nuovo partner è ___" },
  { id: 41, text: "Perché è impossibile mantenere una relazione a distanza per più di sei mesi? ___" },
  { id: 42, text: "Il modo più veloce per far finire una serata romantica nel peggiore dei modi è ___" },
  { id: 43, text: "Cosa non si fa mai in un hotel quando le pareti sono sottili? ___" },
  { id: 44, text: "Il peggior regalo da fare a un partner nel giorno del vostro anniversario è ___" },
  { id: 45, text: "Come si riconosce qualcuno che è bravo a letto prima ancora di andarci? ___" },
  { id: 46, text: "La cosa che fa calare il desiderio più in fretta è ___" },
  { id: 47, text: "Cosa pensa veramente il gatto quando entrate in camera e chiudete la porta? ___" },
  { id: 48, text: "Il modo più sicuro per perdere un amico è ___" },
  { id: 49, text: "Come si rompe il ghiaccio con qualcuno di molto attraente che non conosci? ___" },
  { id: 50, text: "Il modo più imbarazzante per fare una proposta di matrimonio è ___" },
  { id: 51, text: "La cosa peggiore che può succedere durante una serata hot è ___" },
  { id: 52, text: "Come si convince il partner a provare qualcosa di nuovo a letto? ___" },
  { id: 53, text: "Cosa succede quando il nonno scopre cos'è OnlyFans? ___" },
  { id: 54, text: "La migliore scusa per non dormire a casa propria è ___" },
  { id: 55, text: "Il peggior consiglio sessuale che si possa dare a qualcuno è ___" },
  { id: 56, text: "Come si diventa famosi in Italia senza talento ma con molto altro? ___" },
  { id: 57, text: "La cosa più noiosa che un partner possa fare a letto è ___" },
  { id: 58, text: "Cosa succede in Italia tra le 14:00 e le 16:00 mentre tutti fingono di dormire? ___" },
  { id: 59, text: "Il peggior compagno di vacanza romantica è ___" },
  { id: 60, text: "Come si reagisce quando mandi un nudo alla persona sbagliata? ___" },
  { id: 61, text: "Cosa fa un italiano bloccato in casa con il partner per tre settimane? ___" },
  { id: 62, text: "Il modo più efficace per rovinare una serata che stava andando benissimo è ___" },
  { id: 63, text: "Come fai a capire che sei invecchiato/a sessualmente? ___" },
  { id: 64, text: "La cosa più pericolosa da fare quando sei ubriaco/a e hai il telefono in mano è ___" },
  { id: 65, text: "Cosa fa il nonno quando trova il profilo Instagram della nipote con le foto in bikini? ___" },
  { id: 66, text: "Il modo più creativo per essere licenziato/a dopo una notte con il/la collega è ___" },
  { id: 67, text: "Come si rovina un pranzo domenicale con la famiglia rivelando qualcosa di troppo? ___" },
  { id: 68, text: "La scusa migliore per non fare sesso il mercoledì sera è ___" },
  { id: 69, text: "Cosa succede al primo appuntamento quando ti rendi conto che è bellissimo/a ma noioso/a? ___" },
  { id: 70, text: "Il modo peggiore per fare bella figura con i suoceri nel primo weekend insieme è ___" },
  { id: 71, text: "La cosa più stupida che si fa per conquistare qualcuno è ___" },
  { id: 72, text: "Cosa pensa il cane quando i padroni litigano per colpa del sesso? ___" },
  { id: 73, text: "Il segreto per mantenere una relazione appassionante dopo i primi tre mesi è ___" },
  { id: 74, text: "La cosa che tutti fanno da soli ma nessuno ammette mai è ___" },
  { id: 75, text: "Cosa succede se proponi al partner una fantasia che lui/lei non si aspettava? ___" },
  { id: 76, text: "Il modo più creativo per vendicarsi di un ex che ti ha tradito è ___" },
  { id: 77, text: "Come si reagisce quando scopri che il vicino ti sente attraverso il muro? ___" },
  { id: 78, text: "La cosa più drammatica che può capitare durante una vacanza romantica è ___" },
  { id: 79, text: "Cosa fa un italiano quando incontra qualcuno di bellissimo in vacanza all'estero? ___" },
  { id: 80, text: "Il peggior modo per iniziare una relazione con un/a collega è ___" },
  { id: 81, text: "Come si sopravvive a una notte in treno accanto a qualcuno di attraente che russa? ___" },
  { id: 82, text: "La cosa più bella del sesso con la persona giusta è ___" },
  { id: 83, text: "Come si conquistano i genitori del/la fidanzato/a quando sai che sanno già tutto? ___" },
  { id: 84, text: "Il modo migliore per iniziare il lunedì mattina dopo un weekend di fuoco è ___" },
  { id: 85, text: "Cosa ti fa capire definitivamente che una relazione è finita? ___" },
  { id: 86, text: "Il peggior momento per dire 'ti amo' per la prima volta è ___" },
  { id: 87, text: "Come si reagisce quando l'ex si rifà e diventa irresistibile? ___" },
  { id: 88, text: "La cosa che nessun italiano ammetterà mai di fare da solo/a è ___" },
  { id: 89, text: "Il modo migliore per far sì che una storia di una notte non diventi un problema è ___" },
  { id: 90, text: "Cosa succede quando porti a casa qualcuno e il coinquilino è ancora sveglio? ___" },
  { id: 91, text: "Il peggior modo per chiedere al partner di provare qualcosa di nuovo è ___" },
  { id: 92, text: "Come si fa a sembrare esperti a letto anche quando non lo si è? ___" },
  { id: 93, text: "La cosa che manda più in crisi un italiano dopo i 35 anni è ___" },
  { id: 94, text: "Il modo più italiano per rimediare dopo una figuraccia in camera da letto è ___" },
  { id: 95, text: "Cosa fa davvero paura a un uomo italiano di mezza età? ___" },
  { id: 96, text: "Come si capisce se sei al Sud o al Nord dall'approccio al sesso? ___" },
  { id: 97, text: "La cosa peggiore da dire durante una lite di coppia alle 3 di notte è ___" },
  { id: 98, text: "Il modo più creativo per spiegare alla mamma perché non sei tornato/a a dormire è ___" },
  { id: 99, text: "Cosa succede la mattina dopo una notte di sesso con qualcuno che rivedrai in ufficio? ___" },
  { id: 100, text: "Il segreto per essere sempre desiderati è ___" },
]

export const ANSWERS: AnswerCard[] = [
  // ── Sesso e relazioni ──────────────────────────────────────────────────────
  { id: 1, text: "Un pompino silenzioso mentre la suocera è in soggiorno" },
  { id: 2, text: "Scopare con qualcuno di molto più giovane" },
  { id: 3, text: "Il profumo di un ex alle 3 di notte" },
  { id: 4, text: "Fare sesso per la prima volta con la luce accesa" },
  { id: 5, text: "Un orgasmo finto così bene da meritare un Oscar" },
  { id: 6, text: "Il preservativo che si rompe il giorno prima delle ferie" },
  { id: 7, text: "Mandare nudi per sbaglio al gruppo di famiglia" },
  { id: 8, text: "Il vibratore trovato dalla mamma nelle valigie" },
  { id: 9, text: "Una milf con l'ansia da prestazione" },
  { id: 10, text: "Il momento in cui capisci che anche il/la vicino/a sente tutto" },
  { id: 11, text: "Fare l'amore con il costume ancora mezzo addosso" },
  { id: 12, text: "Il sesso di riconciliazione dopo una lite epica" },
  { id: 13, text: "Un cazzo dipinto da Michelangelo sulla Sistina" },
  { id: 14, text: "Scoparsi l'istruttore di fitness perché 'è compreso nel pacchetto'" },
  { id: 15, text: "Il cugino di cui non parli mai ma che è bellissimo" },
  { id: 16, text: "Una serata su OnlyFans per pagare l'affitto" },
  { id: 17, text: "Il sextape girato con un iPhone 6 da 16 GB" },
  { id: 18, text: "Fare sesso orale mentre ascolti il rosario in radio" },
  { id: 19, text: "La pillola del giorno dopo al bar con il cappuccino" },
  { id: 20, text: "Un orgasmo multiplo che dura quanto un episodio di Black Mirror" },
  { id: 21, text: "Il ragazzo con le mani grandi e le scarpe grandi" },
  { id: 22, text: "Una notte a Barcellona di cui ricordi solo i primi 20 minuti" },
  { id: 23, text: "Il coinquilino che sente tutto attraverso il muro sottile" },
  { id: 24, text: "Scopare al concerto sotto la giacca a vento" },
  { id: 25, text: "Un app di incontri aperta durante il pranzo di famiglia" },
  { id: 26, text: "Il reggiseno tolto con una mano sola senza guardare" },
  { id: 27, text: "La valutazione da 4 stelle su Tinder con 'ma sei ok'" },
  { id: 28, text: "La lingua di fuori come risposta a tutto" },
  { id: 29, text: "Un geloso che controlla il telefono mentre dormi" },
  { id: 30, text: "Fare sesso in macchina come se avessimo ancora 17 anni" },
  // ── Corpo e funzioni biologiche ────────────────────────────────────────────
  { id: 31, text: "Un peto durante la meditazione yoga" },
  { id: 32, text: "Il pene che si dimentica di funzionare nel momento clou" },
  { id: 33, text: "Una scoreggia silenziosissima in ascensore pieno" },
  { id: 34, text: "Il morso sul cuscino per non urlare" },
  { id: 35, text: "Alzarsi in piena notte per andare al bagno e svegliarsi di più" },
  { id: 36, text: "Il rutto cronico dopo tre birre" },
  { id: 37, text: "Una pipì sull'autostrada senza autogrill disponibile" },
  { id: 38, text: "Le emorroidi che fanno capolino durante le vacanze" },
  { id: 39, text: "Un orgasmo involontario durante la visita medica" },
  { id: 40, text: "Il ciclo arrivato in bianco durante la cena romantica" },
  { id: 41, text: "Russare così forte da svegliarsi da soli" },
  { id: 42, text: "Il mal di pancia dopo la quarta birra e prima del pullman" },
  { id: 43, text: "La barba pubica non curata da mesi" },
  { id: 44, text: "Un'erezione indesiderata durante la presentazione in ufficio" },
  { id: 45, text: "Il sudore da ansia durante il primo bacio" },
  { id: 46, text: "Scorreggiare e sentirlo caldo — non è un buon segno" },
  { id: 47, text: "Il capezzolo che spunta dalla camicia bianca in riunione" },
  // ── Alcol e feste ──────────────────────────────────────────────────────────
  { id: 48, text: "Ubriaco fradicio alla cena di Natale con i suoceri" },
  { id: 49, text: "Tre shot di tequila e un numero di telefono che non esiste" },
  { id: 50, text: "Il vomito nel taxi con il conducente che non ha i tovagliolini" },
  { id: 51, text: "Ballare sul tavolo a 35 anni come se fosse normale" },
  { id: 52, text: "La bottiglia di prosecco finita da soli davanti a Netflix" },
  { id: 53, text: "Il gin tonic delle 11 di mattina 'perché è domenica'" },
  { id: 54, text: "Svegliarsi nel bagno di qualcuno senza sapere come ci sei finito" },
  { id: 55, text: "Il messaggio imbarazzante mandato alle 2:47 di notte" },
  { id: 56, text: "Fare l'amore con qualcuno di cui non sai il cognome" },
  { id: 57, text: "La sbornia del lunedì che dura fino al mercoledì" },
  { id: 58, text: "Un aperol spritz a colazione 'perché è già l'una'" },
  { id: 59, text: "Il kebab delle 4 di notte mangiato in piedi sul marciapiede" },
  { id: 60, text: "Ubriacarsi al matrimonio del fratello e ballare con la nonna" },
  { id: 61, text: "Il vino economico che fa piangere per un'ora" },
  { id: 62, text: "Cantare Volare nel karaoke fuori tono e orgogliosissimo" },
  { id: 63, text: "Tre grappini per 'scaldarsi' prima di una gita in montagna" },
  { id: 64, text: "Una notte con tequila e senza conseguenze — impossibile" },
  { id: 65, text: "Il collega che si ubriaca alla cena aziendale e balla il floss" },
  { id: 66, text: "Svegliarsi accanto a qualcuno con i vestiti ancora addosso" },
  { id: 67, text: "Prosecco per colazione perché 'i francesi lo fanno'" },
  // ── Famiglia e suoceri ─────────────────────────────────────────────────────
  { id: 68, text: "La suocera che entra in camera senza bussare nel momento sbagliato" },
  { id: 69, text: "Il papà che trova i preservativi nello zaino e non dice nulla" },
  { id: 70, text: "La mamma che chiama durante il sesso con tono urgente" },
  { id: 71, text: "Il cognato che ha il pisello tatuato — lo hai scoperto al mare" },
  { id: 72, text: "La zia che ti chiede se 'vai a letto insieme' al secondo appuntamento" },
  { id: 73, text: "Il nonno che racconta le sue avventure sessative a tavola a Natale" },
  { id: 74, text: "I tuoi genitori che fanno sesso — e lo sai perché senti tutto" },
  { id: 75, text: "La suocera che confronta il seno della nuora con quello della figlia" },
  { id: 76, text: "Il fratello che porta la sua nuova ragazza ogni tre settimane" },
  { id: 77, text: "La zia che commenta il tuo peso ad ogni cena da 15 anni" },
  { id: 78, text: "Il papà che spiega come funzionano i preservativi a 30 anni" },
  { id: 79, text: "La mamma che guarda Donne di Roma e chiede se sei normale" },
  { id: 80, text: "Scoprire che tuo padre ha Tinder" },
  { id: 81, text: "La nonna che porta la crema per le emorroidi come regalo di compleanno" },
  // ── Lavoro e situazioni assurde ────────────────────────────────────────────
  { id: 82, text: "Il capo che ti chiama 'tesoro' in riunione" },
  { id: 83, text: "Scoparsi il capo per avanzare di carriera — e non funziona lo stesso" },
  { id: 84, text: "Il collega che porta foto hot della moglie come sfondo del PC" },
  { id: 85, text: "La videochiamata col cliente partita per sbaglio in bagno" },
  { id: 86, text: "Il collega che viene al lavoro ubriaco di venerdì e rende l'atmosfera festiva" },
  { id: 87, text: "Fare sesso in ufficio dopo che tutti sono andati via — classico" },
  { id: 88, text: "Il CV con 'appassionato di nudismo' tra gli hobby" },
  { id: 89, text: "Una riunione di lavoro interrotta dal vibratore nella borsa" },
  { id: 90, text: "Il team building che finisce in orgia al villaggio" },
  { id: 91, text: "Il collega che manda email di lavoro alle 2 di notte in mutande" },
  // ── Relazioni e appuntamenti ────────────────────────────────────────────────
  { id: 92, text: "L'ex che ricompare solo di notte con 'sei sveglio/a?'" },
  { id: 93, text: "Il ghosting dopo tre mesi e due weekend a Parigi" },
  { id: 94, text: "Il messaggio 'vieni a dormire' alle 23:48" },
  { id: 95, text: "L'ex che si è rimesso/a meglio di te e ti segue ancora" },
  { id: 96, text: "Una storia di 5 anni finita via messaggio durante il pranzo" },
  { id: 97, text: "Il 'mi piace' accidentale su una foto del 2017 dell'ex" },
  { id: 98, text: "Il primo appuntamento con qualcuno trovato su Tinder che assomiglia a tua cugina" },
  { id: 99, text: "La sessione di sesso lampo tra una call e l'altra in smart working" },
  { id: 100, text: "Il fidanzato che scompare per tre giorni e torna come se niente fosse" },
  { id: 101, text: "Il messaggio 'sei la persona più bella che abbia mai visto' da un account senza foto" },
  { id: 102, text: "Innamorarsi di qualcuno durante un piano di vendetta" },
  { id: 103, text: "Il sesso di addio che dura più della relazione intera" },
  { id: 104, text: "L'amore a distanza con tre fusi orari di differenza" },
  { id: 105, text: "Scoprire che il tuo crush ha un/una fidanzato/a da 4 anni" },
  { id: 106, text: "Fare la spesa insieme per la prima volta — momento di crisi garantito" },
  { id: 107, text: "Il primo litigio per il tubetto del dentifricio" },
  { id: 108, text: "Fingere di dormire per non fare sesso il mercoledì sera" },
  { id: 109, text: "Il tradimento scoperto grazie a un'emoji nel posto sbagliato" },
  { id: 110, text: "Guardare insieme il profilo di un ex su Instagram in silenzio" },
  // ── Corpo e autostima ──────────────────────────────────────────────────────
  { id: 111, text: "Il reggiseno che lascia i segni rossi per tre ore" },
  { id: 112, text: "Cercare di fare il/la seducente con le calze di lana ai piedi" },
  { id: 113, text: "Il pelo sul petto che diventa argomento di discussione a tavola" },
  { id: 114, text: "Le maniglie dell'amore che appaiono a 30 anni senza preavviso" },
  { id: 115, text: "Il broncoabbronzato irregolare visto dal partner per la prima volta" },
  { id: 116, text: "La depilazione laser nei posti dove fa più male" },
  { id: 117, text: "Lo specchio del camerino che non perdona" },
  { id: 118, text: "Il tatuaggio sbagliato in un posto che non puoi mostrare al medico" },
  { id: 119, text: "Il secondo mento che appare nelle fotografie" },
  { id: 120, text: "Scoprire i capelli grigi in posti inaspettati" },
  // ── Tecnologia e social ────────────────────────────────────────────────────
  { id: 121, text: "Le foto compromettenti nel cloud condiviso con la famiglia" },
  { id: 122, text: "Il porno aperto per sbaglio in modalità schermo intero durante la riunione" },
  { id: 123, text: "Il messaggio hot mandato alla chat sbagliata" },
  { id: 124, text: "Il profilo fake su Tinder creato per spiare l'ex" },
  { id: 125, text: "La cronologia del browser che il tecnico del computer ha visto tutta" },
  { id: 126, text: "Il telefono sbloccato passato per sbaglio alla suocera" },
  { id: 127, text: "Il nudo inviato al numero sbagliato — e lui risponde entusiasta" },
  { id: 128, text: "Scoprire che il tuo partner ha un profilo su Onlyfans" },
  { id: 129, text: "Le notifiche di Grindr che appaiono durante la proiezione sul proiettore" },
  { id: 130, text: "Il selfie osé salvato nei preferiti della galleria — trovato dal figlio" },
  // ── Cibo e vizi italiani ───────────────────────────────────────────────────
  { id: 131, text: "Mangiare la pizza in modo oscenamente soddisfacente" },
  { id: 132, text: "Il salame piccante che porta conseguenze inattese la mattina dopo" },
  { id: 133, text: "Fare una dieta e cedere alla carbonara come a un amante di ritorno" },
  { id: 134, text: "L'amaro digestivo che diventa bottiglia intera" },
  { id: 135, text: "Il tiramisù mangiato direttamente dalla pirofila alle 2 di notte" },
  { id: 136, text: "La bistecca al sangue con la stessa faccia di chi ha appena fatto sesso" },
  { id: 137, text: "Finire il limoncello della nonna durante la videochiamata di famiglia" },
  { id: 138, text: "Il cornetto con crema e Nutella dopo una notte in bianco" },
  { id: 139, text: "La parmigiana di melanzane mangiata sul divano in mutande" },
  { id: 140, text: "Il capretto di Pasqua che fa piangere tutti prima di mangiarlo" },
  // ── Umorismo nero e situazioni assurde ─────────────────────────────────────
  { id: 141, text: "Il preservativo scaduto nel cassetto dal 2019" },
  { id: 142, text: "La chat di coppia piena di cuori e poi improvvisamente vuota" },
  { id: 143, text: "Scopare e poi discutere su chi lava le lenzuola" },
  { id: 144, text: "Il/la terzo/a incomodo/a che non capisce di essere il terzo incomodo" },
  { id: 145, text: "La proposta di matrimonio rifiutata in pubblico davanti a 200 persone" },
  { id: 146, text: "Il divorzio spiegato ai figli con l'aiuto di Peppa Pig" },
  { id: 147, text: "L'assegno di mantenimento che non copre neanche il Campari" },
  { id: 148, text: "La terapia di coppia che convince solo il terapeuta a divorziare" },
  { id: 149, text: "Un figlio a 47 anni 'per tenere il matrimonio'" },
  { id: 150, text: "La crisi di mezza età con la moto e l'amante di 24 anni" },
  { id: 151, text: "Scoprire di avere un fratellastro grazie a 23andMe" },
  { id: 152, text: "Il padre biologico che spunta a Natale dopo 30 anni" },
  { id: 153, text: "Il testamento che spacca la famiglia peggio di qualsiasi guerra" },
  { id: 154, text: "La suocera che muore e lascia tutto al cane" },
  { id: 155, text: "Il fidanzato arrestato al check-in per imbarazzo internazionale" },
  // ── Situazioni piccanti ─────────────────────────────────────────────────────
  { id: 156, text: "Il letto dell'albergo che cigola e il vicino che bussa alle 2" },
  { id: 157, text: "Una stripteaser al compleanno che conosce il festeggiato troppo bene" },
  { id: 158, text: "Il massaggio tantra prenotato per sbaglio alla spa aziendale" },
  { id: 159, text: "Le mutande trovate in una borsa dell'IKEA senza spiegazioni" },
  { id: 160, text: "Il linguerie comprato online che arriva tre taglie più grande" },
  { id: 161, text: "Il rumore del letto che convince i figli a mettere le cuffie" },
  { id: 162, text: "La posizione tentata a 40 anni che richiede una visita dall'osteopata" },
  { id: 163, text: "Il bikini perso in mare durante la nuotata — e devi tornare a riva" },
  { id: 164, text: "L'hotel che fornisce accessori 'per adulti' nel minibar" },
  { id: 165, text: "Il massaggiatore che capisce l'italiano meglio di quanto pensavi" },
  { id: 166, text: "La doccia insieme che finisce con la perdita di un contatto" },
  { id: 167, text: "Il Capodanno a Praga che non puoi raccontare a nessuno" },
  { id: 168, text: "Il vibratore che squilla durante il controllo in aeroporto" },
  { id: 169, text: "Le handcuffs trovate dalla cameriera dell'hotel" },
  { id: 170, text: "Una notte in agriturismo con letto a una piazza e mezza" },
  // ── Coppia e convivenza ─────────────────────────────────────────────────────
  { id: 171, text: "Il partner che scoreggia tranquillamente dopo sei mesi di convivenza" },
  { id: 172, text: "Litigare per chi dorme sul lato bagnato" },
  { id: 173, text: "Il sesso con i calzini ai piedi perché fa troppo freddo" },
  { id: 174, text: "La moglie/marito che dice 'fai tu' per tutto tranne il telecomando" },
  { id: 175, text: "Il piano di seduzione fallito perché sei già addormentato alle 22:30" },
  { id: 176, text: "La libreria IKEA montata insieme — causa principale di divorzio" },
  { id: 177, text: "Fare pace dopo una litigio con del sesso furibondo" },
  { id: 178, text: "Dormire sul bordo del letto per tre mesi dopo un litigio" },
  { id: 179, text: "Il silenzio in macchina che vale mille parole" },
  { id: 180, text: "Scoprire che tuo marito/moglie guarda il porno che guardi tu" },
  { id: 181, text: "La notte in cui entrambi fingerete di non volerlo ma poi..." },
  { id: 182, text: "Il compleanno del partner dimenticato e recuperato con il sesso" },
  { id: 183, text: "Decidere di non avere figli — e poi cambiare idea alle 38:00" },
  { id: 184, text: "Il tradimento con il personal trainer 'di entrambi'" },
  { id: 185, text: "La crisi di coppia risolta da un weekend a Bali" },
  // ── Vizi e cattive abitudini ───────────────────────────────────────────────
  { id: 186, text: "Fumare sul balcone di nascosto come un adolescente a 42 anni" },
  { id: 187, text: "La canna sul balcone del b&b di fronte alla chiesa" },
  { id: 188, text: "Il sesto bicchiere di rosso 'perché fa bene al cuore'" },
  { id: 189, text: "Lo spin del vino da tre euro acquistato 'solo per cucinare'" },
  { id: 190, text: "Spendere tutto lo stipendio in una sola serata di sabato" },
  { id: 191, text: "Giocare alle slot alle 10 di mattina al bar mentre aspetti il caffè" },
  { id: 192, text: "Il gratta e vinci comprato in segreto ogni giorno" },
  { id: 193, text: "Il video di TikTok guardato alle 3 di notte che dura 40 minuti" },
  { id: 194, text: "Comprare oggetti costosi online ubriaco e scoprirlo il giorno dopo" },
  { id: 195, text: "Fare la spesa affamato e tornare con tre pezze di formaggio e niente di utile" },
  // ── Situazioni italiane +18 ────────────────────────────────────────────────
  { id: 196, text: "La passeggiata delle 5 di mattina con gli abiti della sera prima" },
  { id: 197, text: "Il controllore del treno che ti trova senza biglietto e senza scuse" },
  { id: 198, text: "Nudismo involontario alla sagra del paese" },
  { id: 199, text: "Il prete che parla di castità mentre tu pensi a sabato sera" },
  { id: 200, text: "Le terme di Saturnia con persone che non vorresti vedere nude" },
  { id: 201, text: "Il confessionale in cui sei troppo onesto e lo sconcerti" },
  { id: 202, text: "L'idraulico che arriva mentre sei ancora a letto con qualcuno" },
  { id: 203, text: "Il postino che suona nel momento peggiore possibile" },
  { id: 204, text: "Il vicino nudista che saluta dal balcone ogni mattina" },
  { id: 205, text: "La spiaggia nudista trovata per sbaglio con i suoceri" },
  { id: 206, text: "Il cameriere del bed and breakfast che sa tutto" },
  { id: 207, text: "Dormire con qualcuno e scoprire che russa come un tir" },
  { id: 208, text: "Il taxi che parte mentre litighi con qualcuno sul marciapiede" },
  { id: 209, text: "Il parcheggio underground con telecamere che non sapevi ci fossero" },
  { id: 210, text: "La polizia che bussa mentre stai facendo qualcosa di legale ma imbarazzante" },
  // ── Extra piccante ─────────────────────────────────────────────────────────
  { id: 211, text: "Una fantasia che non riesci a spiegare neanche al terapeuta" },
  { id: 212, text: "Il porno italiano anni '80 trovato nelle cassette del nonno" },
  { id: 213, text: "Fare l'amore sul balcone — finché il vicino non applaude" },
  { id: 214, text: "La telefonata erotica finita sulla segreteria telefonica sbagliata" },
  { id: 215, text: "Il sito adult che appare nella cronologia aziendale" },
  { id: 216, text: "Scoprire che il tuo partner ha una lista di desideri su Amazon per adulti" },
  { id: 217, text: "La conversazione WhatsApp piccante inoltrata al gruppo sbagliato" },
  { id: 218, text: "Il romanzo erotico letto in metro con la copertina capovolta" },
  { id: 219, text: "La libreria per adulti visitata 'solo per curiosità' — tre volte" },
  { id: 220, text: "Il massaggio a quattro mani che diventa qualcos'altro in Thailandia" },
  // ── Più spinte ─────────────────────────────────────────────────────────────
  { id: 221, text: "Un threesome organizzato male e concluso con imbarazzo generale" },
  { id: 222, text: "La bondage fatta con i lacci delle scarpe perché non si trova altro" },
  { id: 223, text: "Il gioco di ruolo interrotto da una telefonata della mamma" },
  { id: 224, text: "Il feticismo dei piedi spiegato ai parenti durante le feste" },
  { id: 225, text: "La storia su Wattpad scritta su di te dall'ex" },
  { id: 226, text: "Il porno home-made ritrovato su una vecchia chiavetta USB" },
  { id: 227, text: "Una notte in un sex hotel in Giappone senza capire i comandi" },
  { id: 228, text: "Il giocattolo per adulti regalato dalla migliore amica come scherzo" },
  { id: 229, text: "L'app di incontri che notifica alla stessa persona tre volte di fila" },
  { id: 230, text: "Il workshop 'tantrico' che è solo gente vestita che respira" },
  // ── Vita adulta e responsabilità ───────────────────────────────────────────
  { id: 231, text: "L'IMU non pagata da quattro anni" },
  { id: 232, text: "Il mutuo trentennale firmato a 28 anni in preda al panico" },
  { id: 233, text: "La dichiarazione dei redditi compilata a caso e incrociando le dita" },
  { id: 234, text: "Il fondo pensione che non sarà mai abbastanza" },
  { id: 235, text: "Il condominio in guerra per il parcheggio da quindici anni" },
  { id: 236, text: "La rata dell'auto nuova che non puoi permetterti ma hai comprato lo stesso" },
  { id: 237, text: "Il lavoro in nero spiegato alla guardia di finanza con un sorriso" },
  { id: 238, text: "Il notaio che costa più della casa" },
  { id: 239, text: "L'avvocato del divorzio che guadagna più di entrambi messi insieme" },
  { id: 240, text: "Le spese condominiali che aumentano ogni anno senza migliorare niente" },
  // ── Ironia sociale ─────────────────────────────────────────────────────────
  { id: 241, text: "Il politico che parla di valori familiari con l'amante nascosta" },
  { id: 242, text: "Il prete dell'oratorio che gioca a Fortnite" },
  { id: 243, text: "La farmacista che ti guarda strano quando compri i preservativi" },
  { id: 244, text: "Il medico che ti chiede quante partner hai avuto con la porta aperta" },
  { id: 245, text: "La barista che conosce le tue abitudini meglio di tua moglie" },
  { id: 246, text: "Il ginecologo che non capisce perché sei imbarazzata" },
  { id: 247, text: "L'andrologo con le mani fredde" },
  { id: 248, text: "Il professore che dà la sufficienza perché sei bellissima" },
  { id: 249, text: "L'avvocato che dice 'ci penso io' e poi non fa niente" },
  { id: 250, text: "Il meccanico che guarda il decolté invece del motore" },
  // ── Vacanze e viaggi ────────────────────────────────────────────────────────
  { id: 251, text: "La camera d'albergo con il muro sottile e vicini molto attivi" },
  { id: 252, text: "Il topless in spiaggia che crea un incidente diplomatico" },
  { id: 253, text: "La notte in tenda con qualcuno che hai appena conosciuto al festival" },
  { id: 254, text: "Il viaggio di nozze rovinato dal mal di pancia di entrambi" },
  { id: 255, text: "La guida turistica di Praga che propone un giro extra a pagamento" },
  { id: 256, text: "Il ristorante in Grecia dove la cucina è pessima ma il cameriere no" },
  { id: 257, text: "La notte sull'hamac tra due palme con le zanzare come terzo incomodo" },
  { id: 258, text: "Il villaggio vacanze dove il 'tutto incluso' include troppo" },
  { id: 259, text: "La crociera in cui incontri tutti i tuoi ex nello stesso corridoio" },
  { id: 260, text: "L'appartamento Airbnb con la telecamera nascosta trovata dopo due notti" },
  // ── Umorismo crudo ─────────────────────────────────────────────────────────
  { id: 261, text: "La doccia fredda per calmarsi — non funziona mai" },
  { id: 262, text: "Il preservativo gonfio come un palloncino trovato nel cestino" },
  { id: 263, text: "La posizione impossibile vista su internet e provata con scarso successo" },
  { id: 264, text: "Il letto che si rompe — e devi chiamare il falegname la mattina dopo" },
  { id: 265, text: "Fare sesso quando i bambini dormono — e poi sentirli svegliarsi" },
  { id: 266, text: "La mattina dopo senza ricordare come ci si è tolte le scarpe" },
  { id: 267, text: "Il moccio allergico durante un momento romantico" },
  { id: 268, text: "Il morso sul collo che devi nascondere alla cena aziendale" },
  { id: 269, text: "Lo strappo muscolare durante un momento di passione — e le spiegazioni al pronto soccorso" },
  { id: 270, text: "L'amico che non bussa mai prima di entrare" },
  // ── Drammi quotidiani +18 ──────────────────────────────────────────────────
  { id: 271, text: "La telefonata dell'ex mentre sei a letto con qualcun altro" },
  { id: 272, text: "Il rossetto sul colletto spiegato alla moglie senza convinzione" },
  { id: 273, text: "La prova di gravidanza positiva trovata nel bagno dell'ufficio" },
  { id: 274, text: "Il figlio che trova la rivista sotto il materasso" },
  { id: 275, text: "La suocera che lava i panni e trova qualcosa di inaspettato" },
  { id: 276, text: "Il profumo sbagliato sul maglione dopo una 'riunione di lavoro'" },
  { id: 277, text: "La foto compromettente tagliata male su Instagram" },
  { id: 278, text: "Il conoscente che ti riconosce in un posto dove non avresti dovuto essere" },
  { id: 279, text: "Il cerotto in un posto che devi spiegare senza dire la verità" },
  { id: 280, text: "La borsetta lasciata a casa di qualcuno che devi recuperare presto" },
  // ── Vita notturna ──────────────────────────────────────────────────────────
  { id: 281, text: "La discoteca a 40 anni dove la musica è troppo forte e i piedi fanno male" },
  { id: 282, text: "Il buttafuori che ti lascia passare per motivi sbagliati" },
  { id: 283, text: "Il cocktail da 18 euro che sai che vale tre" },
  { id: 284, text: "Il bagno della discoteca dove succede di tutto" },
  { id: 285, text: "L'after dalle 5 in un appartamento di 40 mq con 30 persone" },
  { id: 286, text: "Il Capodanno finito a litigare con qualcuno che hai appena conosciuto" },
  { id: 287, text: "L'alba vista dal lungolago con qualcuno di sbagliato ma bellissimo" },
  { id: 288, text: "Il taxi alle 6 di mattina con i tacchi in mano e il mascara sfatto" },
  { id: 289, text: "La festa in piscina in cui qualcuno ha tolto troppo" },
  { id: 290, text: "Il reggiseno trovato nel giardino il giorno dopo la festa" },
  // ── Italia piccante ────────────────────────────────────────────────────────
  { id: 291, text: "Il ragazzo di Napoli con le mani d'oro" },
  { id: 292, text: "Il romano che pensa di essere il più bello della stanza" },
  { id: 293, text: "Il milanese con la Porsche e il complesso di inferiorità" },
  { id: 294, text: "Il siciliano geloso che si è sposato per risolvere il problema" },
  { id: 295, text: "La veneta che beve il prosecco a colazione e giudica nessuno" },
  { id: 296, text: "Il toscano che parla di sesso come se stesse descrivendo un vino" },
  { id: 297, text: "La bolognese che cucina la pasta migliore e sa usarla come arma" },
  { id: 298, text: "Il pugliese che non tradisce mai — tranne il martedì" },
  { id: 299, text: "Il fiorentino con il palazzo di famiglia e le cambiali segrete" },
  { id: 300, text: "La catanese che fa la martire ma poi vince sempre" },
  // ── Situazioni universali ──────────────────────────────────────────────────
  { id: 301, text: "Iniziare a piangere durante il sesso e dover spiegare che stai bene" },
  { id: 302, text: "Addormentarsi durante l'atto — e svegliarsi con il partner offeso" },
  { id: 303, text: "Ridere in modo incontrollabile nel momento meno appropriato" },
  { id: 304, text: "Chiamare il partner col nome sbagliato — in qualsiasi contesto" },
  { id: 305, text: "Il crampo al piede che ferma tutto nel momento peggiore" },
  { id: 306, text: "Capire che sei ancora innamorato/a dell'ex nel mezzo di un appuntamento" },
  { id: 307, text: "Il 'ti amo' detto troppo presto e rimasto sospeso nell'aria" },
  { id: 308, text: "Scoprire di avere gli stessi gusti musicali — e rovinare il mistero" },
  { id: 309, text: "La gelosia che trasforma una serata normale in un thriller" },
  { id: 310, text: "Il pianto post-orgasmico che non sai come spiegare" },
  // ── Extra ──────────────────────────────────────────────────────────────────
  { id: 311, text: "L'ex che ti scrive 'sto bene, grazie per chiederlo' senza che tu abbia chiesto" },
  { id: 312, text: "La terapia individuale che rivela che il problema sei tu" },
  { id: 313, text: "Il momento in cui guardi il/la tuo/a partner dormire e pensi al divorzio" },
  { id: 314, text: "Il matrimonio senza sesso da due anni 'per mancanza di tempo'" },
  { id: 315, text: "L'amante che vuole conoscere la famiglia" },
  { id: 316, text: "Il pene disegnato sul muro del bagno del ristorante stellato" },
  { id: 317, text: "La coppia aperta che non funziona perché uno dei due non era d'accordo" },
  { id: 318, text: "Il giorno in cui realizzi che il tuo tipo è sempre la stessa persona con nomi diversi" },
  { id: 319, text: "Il confine tra romantico e stalking attraversato senza accorgersene" },
  { id: 320, text: "La crisi identitaria a 35 anni che finisce con un tatuaggio sbagliato" },
  { id: 321, text: "Il cornuto che lo scopre per ultimo — come sempre" },
  { id: 322, text: "La moglie che sa tutto e dice niente da dieci anni" },
  { id: 323, text: "Il sesso come punizione — raro ma efficace" },
  { id: 324, text: "La vendetta dell'ex postata su TikTok con 2 milioni di visualizzazioni" },
  { id: 325, text: "L'amico che ti presenta la sua nuova ragazza — è la tua ex" },
  { id: 326, text: "Il sogno erotico sul collega che rende il lunedì mattina insopportabile" },
  { id: 327, text: "Il lapsus in riunione che rivela troppo" },
  { id: 328, text: "La vita erotica del vicino trasmessa in HD attraverso il muro" },
  { id: 329, text: "Il tatuaggio del nome dell'ex coperto male con un fiore" },
  { id: 330, text: "La notte di sesso che ti ricorda perché non dovresti bere tanto" },
  { id: 331, text: "Il 'non è niente di serio' che dura quattro anni" },
  { id: 332, text: "L'ossessione per l'ex che finisce con il seguire anche il cane su Instagram" },
  { id: 333, text: "Il messaggio 'ci pensiamo su' che significa 'è finita'" },
  { id: 334, text: "Fare sesso al telefono e dimenticare che sei in vivavoce" },
  { id: 335, text: "Il/la coinquilino/a troppo presente nelle tue notti" },
  { id: 336, text: "La camera con le pareti sottili in cui ogni suono è condiviso" },
  { id: 337, text: "Il pensiero dell'ex che arriva nel momento meno opportuno" },
  { id: 338, text: "La app che ti mostra che il tuo match è a 200 metri da casa tua" },
  { id: 339, text: "Il sesso in macchina che fa attivare l'antifurto" },
  { id: 340, text: "La lista dei difetti del partner che cresce dopo cinque anni insieme" },
  { id: 341, text: "Scoprire a 40 anni una preferenza che non sapevi di avere" },
  { id: 342, text: "Il fidanzato/a che vuole guardare il film mentre tu vuoi altro" },
  { id: 343, text: "Il bambino che entra senza bussare e vede più di quanto dovrebbe" },
  { id: 344, text: "L'assenza di sesso per tre mesi mascherata da 'stanchezza'" },
  { id: 345, text: "Il romanzo rosa letto in segreto mentre lui guarda il calcio" },
  { id: 346, text: "La conversazione sulle fantasie che va storta" },
  { id: 347, text: "Il pettegolezzo che rivela l'identità dell'amante del vicino" },
  { id: 348, text: "La notte trascorsa a chattare senza poi concludere niente" },
  { id: 349, text: "Il segno sul collo nascosto con tre strati di fondotinta" },
  { id: 350, text: "Il partner che parla troppo durante il sesso — delle bollette" },
  { id: 351, text: "Scoprire una preferenza dell'ex dalla sua nuova partner" },
  { id: 352, text: "La soap opera sentimentale che è la tua vita da tre anni" },
  { id: 353, text: "Il litigio alle 2 di notte per qualcosa successo nel 2018" },
  { id: 354, text: "Il tentativo di seduzione fallito per colpa dei calzettoni bianchi" },
  { id: 355, text: "Il 'stasera no' detto per 60 sere consecutive" },
  { id: 356, text: "La crisi per il calo del desiderio a cui nessuno vuole parlare" },
  { id: 357, text: "Il tradimento perdonato ufficialmente ma mai davvero dimenticato" },
  { id: 358, text: "La moglie/marito che conosce tutte le tue password e le usa bene" },
  { id: 359, text: "Il fine settimana senza sesso deciso unilateralmente" },
  { id: 360, text: "La proposta di coppia aperta fatta nel momento sbagliato" },
  { id: 361, text: "Il messaggio 'mi manchi' dell'ex arrivato a Natale alle 23:47" },
  { id: 362, text: "Il riavvicinamento all'ex che finisce come sempre" },
  { id: 363, text: "La lite violentissima seguita dal sesso migliore dell'anno" },
  { id: 364, text: "Il partner che ricorda le date importanti solo tramite Facebook" },
  { id: 365, text: "La routine di coppia che esclude il sesso da troppo tempo" },
  { id: 366, text: "Il piano di conquista scopiazzato da un film degli anni '90" },
  { id: 367, text: "Il/la migliore amico/a di lui/lei che ti guarda in modo strano" },
  { id: 368, text: "Il regalo di anniversario che costi troppo per dire 'ho sbagliato'" },
  { id: 369, text: "La vacanza romantica rovinata da una scottatura solare totale" },
  { id: 370, text: "Il sesso sotto la tenda al campeggio — acusticamente condiviso" },
  { id: 371, text: "La dieta pre-matrimonio che finisce con la torta nuziale mangiata da soli" },
  { id: 372, text: "Il rituale notturno di 40 minuti prima di dormire insieme" },
  { id: 373, text: "Scopare e poi guardare serie TV come se niente fosse — la vera intimità" },
  { id: 374, text: "Il partner che si sveglia già arrabbiato senza motivo noto" },
  { id: 375, text: "La frase 'dobbiamo parlare' che anticipa sempre il peggio" },
  { id: 376, text: "Il momento esatto in cui capisci che ha smesso di amarti" },
  { id: 377, text: "Il weekend lungo che finisce con una rottura inaspettata" },
  { id: 378, text: "Scoprire che l'ex ha già un nuovo/a fidanzato/a dopo tre settimane" },
  { id: 379, text: "Il cambia partner fatto per sbaglio durante la gita di gruppo" },
  { id: 380, text: "La gelosia retroattiva per cose successe prima di conoscersi" },
  { id: 381, text: "Il/la ex che a distanza di anni è ancora irresistibile" },
  { id: 382, text: "La prima volta dopo una lunga crisi — imbarazzo garantito" },
  { id: 383, text: "Il tradimento che tutti sapevano tranne te" },
  { id: 384, text: "La rottura inaspettata il giorno del vostro anniversario" },
  { id: 385, text: "L'incontro con l'ex portato/a a casa dai genitori — di tutti" },
  { id: 386, text: "Il post-sesso in cui uno dei due vuole parlare e l'altro vuole dormire" },
  { id: 387, text: "La notte in cui non riuscite a smettere di ridere invece di fare altro" },
  { id: 388, text: "Il silenzio di ritorno a casa dopo una cena andata male" },
  { id: 389, text: "La storia di Natale che non finisce a Natale" },
  { id: 390, text: "Il tipo/a incontrato/a in vacanza che pensi di rivedere — e non rivedi mai" },
  { id: 391, text: "Il lunedì mattina in ufficio dopo il weekend con qualcuno di sbagliato" },
  { id: 392, text: "La crisi esistenziale portata in camera da letto alle 2 di notte" },
  { id: 393, text: "Il sex toy di design che stai spiegando come 'oggetto di design'" },
  { id: 394, text: "La serata romantica interrotta da un notifica dell'ex su Instagram" },
  { id: 395, text: "Il capello lungo trovato nel posto sbagliato da chi ha i capelli corti" },
  { id: 396, text: "Il collega con cui hai avuto una storia e adesso ci lavori fianco a fianco" },
  { id: 397, text: "L'appuntamento al buio organizzato dalla mamma — e non è andata male" },
  { id: 398, text: "La festa di compleanno in cui hai baciato qualcuno che non dovevi" },
  { id: 399, text: "Il tentativo di sexting alle 11 di mattina di un martedì normale" },
  { id: 400, text: "Il cassetto del comodino che non puoi aprire davanti alla mamma" },
  { id: 401, text: "Il rossetto lasciato sul bicchiere di cristallo della suocera" },
  { id: 402, text: "La maglietta dell'ex ancora in giro dopo due anni" },
  { id: 403, text: "Il momento in cui capisci che ti piace qualcuno di assolutamente sbagliato" },
  { id: 404, text: "Il sesso lampo tra una riunione e l'altra in smart working" },
  { id: 405, text: "La cena di gruppo in cui scopri che tutti sapevano tranne te" },
  { id: 406, text: "L'ex che appare nel sogno proprio quando pensavi di averlo/la superato/a" },
  { id: 407, text: "La conversazione imbarazzante con i genitori sulla vita amorosa" },
  { id: 408, text: "Il match su Tinder che è il fratello del tuo migliore amico" },
  { id: 409, text: "La proposta di matrimonio fatta alle 4 di notte dopo una sbornia" },
  { id: 410, text: "Il compleanno passato con qualcuno che non eri sicuro di volere lì" },
  { id: 411, text: "La fotosequenza di 12 anni di ex trovata sul telefono del partner" },
  { id: 412, text: "Il coinquilino che sente tutto e fa finta di niente — da tre anni" },
  { id: 413, text: "La vacanza di 'solo amici' con qualcuno che non è solo un amico" },
  { id: 414, text: "Il momento in cui realizzi che stai cercando il/la tuo/a ex in ogni persona" },
  { id: 415, text: "L'aperitivo che finisce a letto — il mercoledì pomeriggio" },
  { id: 416, text: "Il litigio sul posizionamento del cuscino che dura tre settimane" },
  { id: 417, text: "La scoperta che il/la partner ha un secondo profilo Instagram" },
  { id: 418, text: "Il sesso la mattina prima di un'intervista di lavoro importante" },
  { id: 419, text: "L'incontro con il/la ex nel peggiore giorno possibile della tua vita" },
  { id: 420, text: "Il messaggio 'bello/a dormire' dell'ex spedito alle 4:37" },
  { id: 421, text: "L'amico/a che ti dice 'l'ho sempre saputo' dopo la rottura" },
  { id: 422, text: "La foto di coppia ancora come sfondo del telefono dopo mesi" },
  { id: 423, text: "Il piano di vendetta che non funziona perché sei ancora innamorato/a" },
  { id: 424, text: "La notte in cui vai a dormire senza litigare — e ti svegli preoccupato/a" },
  { id: 425, text: "Il segreto che porta avanti la relazione da tre anni" },
  { id: 426, text: "Il momento esatto in cui capisci che hai fatto una cazzata" },
  { id: 427, text: "La spiegazione al pronto soccorso su come ti sei fatto male" },
  { id: 428, text: "Il fermo immagine del video di TikTok che ti immortala nel peggiore dei modi" },
  { id: 429, text: "L'hashtag sbagliato usato sotto una foto osé" },
  { id: 430, text: "Il momento in cui il Google Maps ti piazza dove non dovresti essere" },
  { id: 431, text: "La prenotazione all'hotel trovata dalla moglie nella cronologia" },
  { id: 432, text: "Il ricevuta della cena per due — quando eri 'in trasferta di lavoro'" },
  { id: 433, text: "L'accappatoio con il logo dell'hotel che non hai mai visitato" },
  { id: 434, text: "La crema solare applicata in un posto che fa nascere domande" },
  { id: 435, text: "Il ritardo spiegato con 'traffico' quando Google Maps dice 5 minuti" },
  { id: 436, text: "La serata tra colleghi che finisce in gossip per sei mesi" },
  { id: 437, text: "Il/la socio/a di lavoro con cui è meglio non mescolare gli affari" },
  { id: 438, text: "La riunione di condominio che degenera in grida e rivelazioni personali" },
  { id: 439, text: "Il vicino che sa tutto — e te lo fa capire in silenzio" },
  { id: 440, text: "Il pettegolezzo che gira in paese da 15 anni e sei tu il protagonista" },
  { id: 441, text: "La confessione ubriaca che non puoi più ritirare" },
  { id: 442, text: "Il gruppo WhatsApp in cui sei finito per sbaglio e sai tutto di tutti" },
  { id: 443, text: "La commessa che ti guarda sapendo che sei lì perché hai combinato qualcosa" },
  { id: 444, text: "La farmacista che abbassa gli occhi sul bancone con discrezione" },
  { id: 445, text: "Il tabaccaio che conosce le tue abitudini dal 2007" },
  { id: 446, text: "Il meccanico che vede la macchina dall'interno e capisce tutto" },
  { id: 447, text: "La colf che trova quello che non dovrebbe trovare e non dice niente" },
  { id: 448, text: "Il portiere del palazzo che sa orari e ospiti meglio dell'anagrafe" },
  { id: 449, text: "Il parrucchiere che diventa psicologo non richiesto" },
  { id: 450, text: "L'amico di infanzia che ti ricorda una versione di te che preferiresti dimenticare" },
  { id: 451, text: "La sera in cui tutto va come non dovrebbe e invece funziona benissimo" },
  { id: 452, text: "Il lunedì in cui sei troppo felice e i colleghi capiscono subito" },
  { id: 453, text: "Il rossore in faccia che tradisce tutto prima che tu apra bocca" },
  { id: 454, text: "Lo sguardo complice tra due persone che sanno una cosa che gli altri non sanno" },
  { id: 455, text: "La storia che inizia come scherzo e finisce sul serio" },
  { id: 456, text: "Il 'tanto non succederà niente' detto prima che succeda tutto" },
  { id: 457, text: "L'estate in cui hai fatto cose che non racconteresti mai d'inverno" },
  { id: 458, text: "La notte di agosto in campagna — senza copertura e senza pensieri" },
  { id: 459, text: "Il primo bacio che non hai pianificato e non dimenticherai mai" },
  { id: 460, text: "La scoperta che con la persona sbagliata ci sono i momenti migliori" },
  { id: 461, text: "Il sorriso di chi sa che ha fatto tardi per i motivi giusti" },
  { id: 462, text: "L'abbraccio alle 6 di mattina prima di tornare a casa propria" },
  { id: 463, text: "La canzone che ti ricorda qualcuno che non ti ricorda più" },
  { id: 464, text: "Il viaggio in motorino alle 3 di notte verso casa di qualcuno" },
  { id: 465, text: "La cena con i genitori il giorno dopo una notte senza dormire" },
  { id: 466, text: "Il silenzio imbarazzante rotto dalla notifica del telefono" },
  { id: 467, text: "La fotografia trovata anni dopo che dice tutto senza parole" },
  { id: 468, text: "L'anniversario dimenticato perché 'non sei il tipo romantico'" },
  { id: 469, text: "La settimana in cui tutto sembra andare bene — e ti spaventa" },
  { id: 470, text: "Il compleanno in cui realizzi che hai esattamente l'età che ti spaventa" },
  { id: 471, text: "La notte in cui decidi di non decidere niente — e poi decidi tutto" },
  { id: 472, text: "Il momento in cui capisci che sei cambiato/a senza averlo pianificato" },
  { id: 473, text: "La conversazione che hai sempre evitato e poi finalmente fai" },
  { id: 474, text: "Il sabato sera in cui resti a casa e non te ne penti" },
  { id: 475, text: "La domenica mattina in cui per una volta non hai fretta" },
  { id: 476, text: "Il gesto stupido che fa capire a qualcuno che ci tieni" },
  { id: 477, text: "La decisione presa di notte che sembra perfetta — e lo è ancora la mattina" },
  { id: 478, text: "L'amico/a che dici solo 'buona notte' e lui/lei capisce tutto" },
  { id: 479, text: "Il momento in cui smetti di fingere e inizi a stare bene davvero" },
  { id: 480, text: "La persona giusta incontrata nel momento completamente sbagliato" },
  { id: 481, text: "L'estate che pensavi sarebbe stata uguale alle altre — e non lo era" },
  { id: 482, text: "Il coraggio di mandare quel messaggio che rimandavi da tre settimane" },
  { id: 483, text: "Il bacio rubato in cucina mentre stai cucinando — la migliore interruzione" },
  { id: 484, text: "La persona a cui pensi quando senti una certa canzone" },
  { id: 485, text: "Il momento in cui capisci che quello che cercavi era già lì" },
  { id: 486, text: "La notte in cui non riesci a dormire — e sai esattamente perché" },
  { id: 487, text: "L'abitudine che hai preso da qualcuno che non c'è più" },
  { id: 488, text: "Il sabato mattina in cui non devi essere da nessuna parte — finalmente" },
  { id: 489, text: "Il tramonto visto con qualcuno di cui non sapevi ancora il cognome" },
  { id: 490, text: "La risata che ti fa piegare in due con la persona giusta" },
  { id: 491, text: "Il messaggio 'tutto ok?' che arriva esattamente quando ne hai bisogno" },
  { id: 492, text: "La serata che non avevi programmato e diventa la migliore dell'anno" },
  { id: 493, text: "Il gesto piccolo che vale più di qualsiasi parola" },
  { id: 494, text: "La persona che ti fa venire voglia di stare sveglio/a più a lungo" },
  { id: 495, text: "Il momento esatto in cui smetti di cercare e trovi" },
  { id: 496, text: "La notte in cui parli per ore senza guardare l'ora" },
  { id: 497, text: "Il caffè condiviso la mattina senza dover dire niente" },
  { id: 498, text: "Lo sguardo che sa già quello che stai per dire" },
  { id: 499, text: "La mano trovata al buio — senza cercarla" },
  { id: 500, text: "Il momento in cui smetti di fingere e qualcuno ti preferisce lo stesso" },
]

export function shuffleArray<T>(array: T[]): T[] {
  const arr = [...array]
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr
}

export function getAnswerById(id: number): AnswerCard | undefined {
  return ANSWERS.find(a => a.id === id)
}

export function getQuestionById(id: number): QuestionCard | undefined {
  return QUESTIONS.find(q => q.id === id)
}
